### ISSUE TITLE
Robots.txt auto generation on install

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1222]
Thus `sitemap` directive added into robots.txt (see 7523f2893e921cbca845baa7350154b5376809cf ) we have ability to autocreate (if write permition granted) robots.txt with certain site url during install. So no addition (hand made) changes required to robots.txt (except uncomment `sitemap` line).

**Comment by Alex300** [comment]
Added automatic creation of directives Sitemap and Host
