### ISSUE TITLE
Improve plugin tags

### ISSUE THREAD

**Issue by Dayver** [Cotonti/Cotonti#1275]
- Tags require administrative panel where you can edit\remove tags (without to editing the hundreds of pages\topics\posts\etc). I already have about 80-90% of finished code but do not have time to complete this work, I propose that I'll put him in the repository site cotonti.com where you guys can help finish it and test it on a large number of content
- The third variant of the config value register first letter of the tag (with old a **large**, **small** and new **as it is**)
- In config plugin can select separator character for the URL now - space is replaced by a dash I suggest giving choice to replace the space on underscore

**Comment by trustmaster** [comment]
Added in a246e59c5801571073aca2a91c339e63df0b5f91
