### ISSUE TITLE
Extrafields Cache Generation Problem

### ISSUE THREAD

**Issue by Kilandor** [Cotonti/Cotonti#1333]
Its a limited case however. I think it is when you edit/create a new category. All cache's are purged. The problem is this can lead to extrafield cache not being generated and breaking anything that uses it. Currenly the cache only seems to be generated when viewing a extrafields config page.

We need some kind of better handling for this.

The only 2 places cot_load_extrafields() is called is in admin.extrafields.php and at the bottom of extrafields.php

**Comment by Alex300** [comment]
Could you more precise explain how I can reproduce the bug?
Thank you.

**Comment by Kilandor** [comment]
The problem was when you edit or create a new category in structure. It would clear the cache. The problem would be that the extrafield cache was not being updated. The problem was fixed in newer versions, I added the empty check incase for some reason the var was ever ()

This can be closed
