### ISSUE TITLE
Use tpl callback with multiple params

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1360]
Extend TPL callbacks to accept multiple (tag) params. 
Like this:
`{PHP|my_widget({PAGE_ID}, {PHP.cat_name}, 'some text')}`
or this way:
`{PHP|my_widget(PAGE_ID, PHP.cat_name, 'some text')}`

**Comment by esclkm** [comment]
may be we need for callbacks new syntax, witch will be more intuitive. Word $this or vars without { } symbols - its 3 types of different syntaxis.
Я like to use 2 type oа callbacks:
{PHP|callback} - with 1 var
[callback: {param1}, {param2}, ...]  - for more than 1 param

**Comment by macik** [comment]
The problem devides for two major parts: 
1. The way of extension: trying to extend current template engine (with backwards comptibility) or trying to rewrite it or heavy extend (for totally different syntax).

2. Using of callback chains — how it would be organized and shlould it be at all.
