### ISSUE TITLE
i18n: Structure list not updated 

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1362]
Structure list for i18n not updated after new category added to pages.

**Comment by Alex300** [comment]
Update i18n structure at change category code fixed.

But when you add a new category - a new record in i18n structure table will be added when you add localized values for it here: index.php?e=i18n&m=structure&l=ru. Not on catregory creation.
))
-----
Обновление структуры i18n при смене кода категории исправил.

А вот при добавлении  новой категории - новая запись в таблице структуры i18n появляется при сохранении для нее локализованных значений тут: index.php?e=i18n&m=structure&l=en . А не при непосредственном создании самой категории.
Это и логично, при добавлении категории плагин не знает какие значения заголовка и описания сохранить для нужных локалей.

Это не мешает работе системы. Если локализованныз значений для данной категории нет, то используется значение по-умолчанию.

Если я что то не так понял, прошу описать по подробнее, что именно работает не так и переоткрыть issue.
