### ISSUE TITLE
Uploaded exrtafield file is replaced!

### ISSUE THREAD

**Issue by devkont** [Cotonti/Cotonti#1379]
It is Very important problem! If the same file to attach to different records, it is simply replaced, although in theory it should be renamed, if the file already exists on the server.

**Comment by Alex300** [comment]
Fixed. Please test it.
-----
Исправлено. Пожалуйста по тестируйте новый код. 
Если будут ошибки или замечания, может соображения по шаблону переименования файлов, то пишите в комментарии.
