### ISSUE TITLE
Show to user that changes of his personal data are saved

### ISSUE THREAD

**Issue by SergeySt85** [Cotonti/Cotonti#1382]
In profile's settings no information is shown when user changes his data. This confuses user as he doesn't understand whether the information about him was changed or not. He either needs to write to technical support with this question or to update the page which takes time and not really useable.

Please add this function.

**Comment by CrazyFreeMan** [comment]
Если изменять пароль то "обновленно" показывает дважды?

**Comment by SergeySt85** [comment]
CrazyFreeMan, да дублируется слово Обновлено.
