### ISSUE TITLE
`Html_cleanup` option breaks some inpage scripts

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1386]
While «cleanup» is enabled
`$cfg['html_cleanup'] = TRUE;`
breaks inpage JS code with Single Line Comments, 
like `// some comment`;

**Comment by trustmaster** [comment]
This is an issue by design. HTML cleanup should not be enabled for sites using unminified embedded scripts.

**Comment by macik** [comment]
Ok. If we find something like «elFinder with CKeditor» we try to fix it in their scripts.
Own `html_cleanup` leave intact for speed reason.
