### ISSUE TITLE
Group auth reset logic while update

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1391]
While we form to update data for group rights in `Admin → Users → User group → Rights`
all data reseted before actual update, see line:
https://github.com/Cotonti/Cotonti/blob/master/system/admin/admin.rights.php#L75

Is it neccessary, as we actually update rights data (imported from form) later in for cycle? 

Current logic breaks rights setted for addition options by some other extensions.

**Comment by Alex300** [comment]
It's is a bug. Because if something will go wrong while saving data we will lost all right settings for this user group.

**Comment by Dr2005alex** [comment]
After the fix, you can't uncheck all the boxes. You can't completely disable permissions
