### ISSUE TITLE
Lang files on Transifex

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1394]
Is files uploaded to [Transifex ](https://www.transifex.com/organization/trustmaster/dashboard/cotonti) are up to date with latest version of Cotonti?

Origin question is here: http://www.cotonti.com/forums?m=posts&q=7863 ( :ru: )

**Comment by trustmaster** [comment]
I've updated en and ru locales with https://github.com/trustmaster/cotlang and http://docs.transifex.com/developer/client

**Comment by macik** [comment]
I think it will be helpfull to post message about it on main of Cotonti.com to get attention. So Users can help faster eliminate untranslated gap on Transifex.
