### ISSUE TITLE
Upgrade minimum requirements to PHP 5.3

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1395]
Was: «Get syntax error with Resources.php on PHP5.2.17»

`Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM, expecting T_VARIABLE in cot918\system\resources.php on line 75`

**Comment by trustmaster** [comment]
PHP 5.2 has been unsupported by PHP team for 4 years: http://php.net/eol.php. No bugfixes, no security updates for 4 years means it is unsafe to continue using it. Looks like it's time to upgrade our requirements to 5.3.

**Comment by Dayver** [comment]
And do not forget to change in https://github.com/Cotonti/Cotonti/blob/master/modules/install/lang/install.en.lang.php#L39 and https://github.com/Cotonti/Cotonti/blob/master/modules/install/lang/install.ru.lang.php#L39

**Comment by macik** [comment]
Also:
fix `functions.php`:
https://github.com/Cotonti/Cotonti/blob/master/system/functions.php#L15-Lundefined

check (and may be delete) `resources.rc.php`:
https://github.com/Cotonti/Cotonti/blob/master/system/resources.rc.php#L124-L130

`install.install.php`:
https://github.com/Cotonti/Cotonti/blob/master/modules/install/inc/install.install.php#L114-L117
https://github.com/Cotonti/Cotonti/blob/master/modules/install/inc/install.install.php#L516-L520

**Comment by Alex300** [comment]
And update documentation: http://www.cotonti.com/docs/start/installation

**Comment by Alex300** [comment]
> check (and may be delete) resources.rc.php:
> https://github.com/Cotonti/Cotonti/blob/master/system/resources.rc.php#L124-L130

Пока оставлено т.к. используется функцией cot_timezone_search();, которая и сама то используется для апгрейда с Genoa. Может уже и она то и не нужна.
