### ISSUE TITLE
Unable to edit news config due to no valid category

### ISSUE THREAD

**Issue by Kilandor** [Cotonti/Cotonti#1415]
If for some reason you are left with no valid news category that exists. Due to the way the JS works you will be unable to add one. You will have to disable jquery, sql add one or other such strange methods.

The problem is due to the JS requires copying an existing category when clicking add. However if no valid category exists then no html will exist to be copied.

A simple solution is to have a hidden template of HTML to copy, or something to that effect.

**Comment by esclkm** [comment]
I think we need remove news plugin from core/ And close issue
