### ISSUE TITLE
Users: Admin user can be deleted

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1424]
Now Users module from user edit form allow to delete Admin user (superadmin, id=1). 
Is that a normal workflow?

I think that's not right and potentially dangerous.

What do you think?

**Comment by Alex300** [comment]
Да, это нормально. Другой администратор имеет те же права что и пользователь с id=1. Почему вообще id должно иметь значение? Важна только принадлежность группе. Никогда не делайте лишних зависимостей.

Пример из жизни:
Клиент заказал сайт. Исполнитель имеет id=1. После передачи сайта, исполнитель больше не нужен. Мало того, он как администратор может получить доступ к сведениям, составляющим коммерческую тайну.
Клиент удаляет учетную запись исполнителя.

Ну и это еще противоречит 3-ей нормальной форме.

**Comment by macik** [comment]
В целом согласен.
