### ISSUE TITLE
Page list: SQL query inconsistency (page count and pagelist)

### ISSUE THREAD

**Issue by devkont** [Cotonti/Cotonti#1433]
Не хватает строки: 
LEFT JOIN $db_users AS u ON u.user_id=p.page_ownerid 
при получении значения $sql_page_count.

https://github.com/Cotonti/Cotonti/blob/master/modules/page/inc/page.list.php#L177

**Comment by Dayver** [comment]
А зачем она там? Мы же в 177 строке получаем количество страниц удовлетворяющих условие WHERE . А вышеназванная строка не вносит никаких фильтрующих функций в выборку-подсчет страниц, а только доп. выборку параметров пользователя добавившего страницу уже в запросе изымающем данные страницы.

**Comment by devkont** [comment]
Если добавлять свои критерии для запроса с учетом полей в таблице users, то и количество нужно пересчитывать правильно. Иначе будет ошибка.

**Comment by devkont** [comment]
Например: если нам нужно получить страницы только тех пользователей, которые принадлежат группе Members. Мы добавляем через хук page.list.query такой критерий: 

$where['onlymembers'] = "u.user_maingrp=4";

Но так как таблица users не определена в запросе на количество записей, то будет ошибка. Но мы не можем просто прописать ее в join_conditions так как в основном запросе будет дублирование.

**Comment by Dayver** [comment]
Ну так а почему тогда не воспользоватся параметром $join_condition ?

**Comment by devkont** [comment]
Выше я объяснил.
