### ISSUE TITLE
Pagination does not work on the page all the tags

### ISSUE THREAD

**Issue by roffun** [Cotonti/Cotonti#1439]
Pagination does not work on the page all the tags if you limit the number of tags on the page in a cloud of tags.
https://www.cotonti.com/forums?m=posts&q=8009

**Comment by Dayver** [comment]
Plz test this https://github.com/Cotonti/Cotonti/commit/98bf026eb62d0f77e3f3d94cd7b781af5f9cd6da commit

**Comment by Roffun** [comment]
Does not help  98bf026 commit

**Comment by macik** [comment]
@Roffun check the forum, please.

**Comment by Roffun** [comment]
I replied to the forum

**Comment by macik** [comment]
Bug present only with `$cfg['easypagenav']` enabled.

**Comment by macik** [comment]
Reopen, as reported here https://github.com/Cotonti/Cotonti/commit/2285300617115b68b28ee368b638c9cca7d4e95a#commitcomment-15164856
