### ISSUE TITLE
Wrong redirect URL

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1448]
Wrong redirect URL in case CMS installed in site subfolder and we tries to redirect to subfolder.

To reproduce:
- install CMS to `site.com/basefolder/`
- try to redirect to subfolder: `cot_redirect('/basefolder/sub');`
  or
- try to login with «i18n» plugin enabled and selected locale (we get redirect to `/basefolder/basefolder/ru`)

Result: 
we get 404 error as we redirected to `site.com/basefolder/basefolder/sub`.

Reason:
`cot_redirect` code, see lines 5100-5110 of `functions.php`.

**Comment by Dr2005alex** [comment]
Судя по всему уже не актуально, проверил.. повторить не смог на текущей версии.
