### ISSUE TITLE
Search not working with i18n

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1449]
Detailed info [here](https://www.cotonti.com/forums?m=posts&q=8018&n=unread#unread) ( :ru: )

Cause:
not complete refatoring in https://github.com/Cotonti/Cotonti/commit/8e8f14cb89b812d828acf6b13551b37566991b3a

**Comment by macik** [comment]
Also `$rs` array structure need to be updated...

**Comment by macik** [comment]
Fixed. Need testing.

**Comment by CrazyFreeMan** [comment]
Уже лучше но не сохраняет выбраный язык при поиске для авторизованого юзера (админа точно) и не все результаты выводит
Есть статья на основном языке - поиск идет все ок, добавляю перевод на второй язык - ищу словами второго языка  - все ок показывает то что нужно. а если буду искать эту статью в оригинальном тексте то ничего не показывает 
Если нужно могу дать сайт для теста

**Comment by macik** [comment]
Давай, желательно с примерами запросов и описанием, что должно найтись в результатах.

**Comment by macik** [comment]
Seems working fine. Closing issue.
