### ISSUE TITLE
use cotonti as phonegap back end

### ISSUE THREAD

**Issue by cabkiddec** [Cotonti/Cotonti#1472]
I am having trouble when I try to login to website that is using cotonti from phonegap. I have tried using ajax, and I have tried using the html that is genertated from login.php. when using post I get a paramaters error and when I am using get it does not redirect to index.php nor login. I can get all of this to work fine in browser but not from phonegap. I have whitelisted my domain in phonegap. I think my issue is that when  I try to use ajax from html login page I am not knowing how the response will look so my success function will not know if I am logged in.

So the question is: Seeing how I cant run php on phonegap android app, If I have a html login page how could I submit the login form to the login.php?a=check and how would I know what the response would look like

**Comment by macik** [comment]
1. Support questions not related certain bag better to ask on official Cotonti support forum:
https://www.cotonti.com/forums?m=topics&s=26
2. The Phonegap is a third party software and I don know internal mechanics if it and can test it. 
3. More over, you was not provide any addiition info like Cotonti and Phonegap version you are using.

Info for further experiments:
1. Login to you site and clear all cache (Admin→Tools→Core)
2. Setup proper cookie domain and path (Admin→Configuration→Session)
3. Check is Phonegap properly served cookies, receive from your site and send it back on a query.
4. By default, there are no AJAX used for login. There are 3 steps: sending form data, authorization, redirect to main page (or visited before).
5. To be successfully authorized you need to send: cookie with session ID, user login (`rusername` parameter), password (`rpassword`) and form protection parameter `x`, that served with login form on login page:

```html
<form method="post" action="login.php?a=check" name="login">
    <div style="display:inline;margin:0;padding:0">
        <input type="hidden" value="53D3CE52" name="x">
    </div>
```
`53D3CE52` in current example.

Here is a request and server response headers log (skipped some misc lines and adding a comments):
```log
# Tries to login with POST request:
http://localhost/cot919/login.php?a=check

POST /cot919/login.php?a=check HTTP/1.1
Host: localhost
Referer: http://localhost/cot919/login.php
Cookie: PHPSESSID=5uspkugqucdo999ccnbgause84;
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 56
# here is POST query parameters with `x` security code
x=53D3CE52&rusername=admin&rpassword=imustbeloggedin

Server answer after authorization:
HTTP/1.1 302 Found
Date: Tue, 26 Jan 2016 20:13:23 GMT
# Here we can see redirect command
Location: http://localhost/cot919/index.php
Content-Length: 0
Content-Type: text/html
----------------------------------------------------------

# Loading index page after redirect:
http://localhost/cot919/index.php

GET /cot919/index.php HTTP/1.1
Host: localhost
Referer: http://localhost/cot919/login.php
Cookie: PHPSESSID=5uspkugqucdo999ccnbgause84; 

HTTP/1.1 200 OK
Date: Tue, 26 Jan 2016 20:13:23 GMT
Content-Type: text/html; charset=UTF-8
```

**Comment by macik** [comment]
@cabkiddec, issue will be closed **7 feb 2016** unless no addition information is provided.
