### ISSUE TITLE
cot_selectbox_theme() treat empty folder as a valid theme

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1485]
If we have some not theme related or even empty folder in `themes` dir, `cot_selectbox_theme()` treat it as a valid theme. It's not right. Invalid themes or foreign folders must not be included in themes list.

**Comment by Dr2005alex** [comment]
It is necessary to check the file in the theme_name.php

**Comment by macik** [comment]
Moreover I propose to force checking of `COT_THEME` block with theme related info.
Now we have weak checking for both `theme_name.php` and `COT_THEME`.
Also propose to add optional `Version` parameter to easy changes tracking and preventing adding any unrelated info into the `Name` parameter.
