### ISSUE TITLE
Preparation to 0.9.19 release

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1494]
To-do list
- [x] fix PHPoc tags (related to #1023 ) and omit closing tags ( #1077 ) for new code
- [x] fix Extensions versions ( #1464)
- [x] update copyright dates where needed
- [x] add README to repo
- [x] bump version to 0.9.19 in core files
- [x] close 0.9.19 milestone issues

**Comment by macik** [comment]
We finally do it...

**Comment by CrazyFreeMan** [comment]
Смотря на активность нужно заменить "We" -> "I" :+1:

**Comment by macik** [comment]
Каждый старается в меру своих возможностей...
