### ISSUE TITLE
User Images: avatar is not displayed

### ISSUE THREAD

**Issue by devkont** [Cotonti/Cotonti#1500]
![2016-03-18 15 37 56](https://cloud.githubusercontent.com/assets/6356524/13878029/a8314308-ed1f-11e5-9760-be66fc9687fc.png)

**Comment by macik** [comment]
I suppose it's caused due to `$R['userimg_img']` not defined in `userimages.resources.php` or redefined (cleared) somewhere in the system (by theme resources or another extension).
Check it please.

**Comment by macik** [comment]
See `cot_userimages_build()` [code](https://github.com/Cotonti/Cotonti/blob/0.9.18.1/plugins/userimages/inc/userimages.functions.php#L135-L156)

**Comment by devkont** [comment]
Сhecked for a clean Cotonti from github.

**Comment by devkont** [comment]
Look at this https://github.com/Cotonti/Cotonti/commit/135062c0d91a9d4cfb7c3bc09ad143a7db09e953#diff-0cc7bb639900e3f1512d2aaa5880b363L138

**Comment by macik** [comment]
@devkont check it please.

**Comment by devkont** [comment]
Now works!
