### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by devkont** [Cotonti/Cotonti#1501]
readdir() expects parameter 1 to be resource, boolean given in .../system/functions.php on line 2603
closedir() expects parameter 1 to be resource, boolean given in .../system/functions.php on line 2610

Cotonti from Github!

**Comment by macik** [comment]
@devkont  Thanks for testing. Try it once more.

**Comment by devkont** [comment]
Good! The problem can be closed! Thank you!
