### ISSUE TITLE
NO_ZERO_DATE in MySQL 5.7

### ISSUE THREAD

**Issue by Alex300** [Cotonti/Cotonti#1505]
NO_ZERO_DATE, and NO_ZERO_IN_DATE SQL modes are now deprecated but enabled by default in MySQL 5.7. Using '0000-00-00' or '0000-00-00 00:00:00' throws an exception. 'NULL' must be used instead.

**Comment by Alex300** [comment]
Rus: Исправлено для модуля "users". Хорошо бы его протестировать, особенно в плане обновления (должен отработать патч: modules/users/setup/patch_1.4.4.sql), а также - регистрации и редактировании пользователя.

P.S. Если Вы перешли на MySQL 5.7 и потом пытаетесь обновиться - скорее всего у Вас ничего не выйдет, т.к. в вашем MySQl уже действуют описанные выше ограничения. Сначала обновить cotonti, потом СУБД.

**Comment by macik** [comment]
Todo:

- [ ] version should be bumped to 1.4.5 or 1.5.0 (and rename patch respectively)
- [ ] `install.sql` should be updated

**Comment by Alex300** [comment]
Rus. А зачем в пределах одного релиза так накручивать номера версий коробочных модулей? Чтобы как в FireFox дойти быстренько до 30-х версий. У тех кто установит обновление 0.9.19 на 0.9.18 патч сработает.
Нет мне не то чтобы жалко цифру сменить. Но логика?

**Comment by macik** [comment]
1. Patch version is supposed to reflect any bug fixes
2. Some users had to renew only certain extensions prior to release, or in cases when updating of whole site to new release is not possible for some reasons.
3. If we use some scripts fetching new changes from master or using some automated or testing environment we need to see certain changes (new version) in extensions list.

**Comment by Alex300** [comment]
Как скажете. Пожалуйста. Вечером. С работы сегодня не выйдет.
Но. 
1) Номер коммита делает тоже самое. И в коммите видно какие изменения внесены и когда.
2) Пользователи, которые обновляются в промежутке между стабильными релизами - явно из разработчиков и могут сами проследить и накатить патчи. Это же не релиз, а версия в разработке.

**Comment by macik** [comment]
Я поясню свою точку зрения:
* есть такое понятие, как семантическое версионирование, которое достаточно четко определяет правила нумерации версий ПО, и говорит, в частности, что если мы фиксим баг (а не просто опечатку в тексте — патч версия должна это отражать. Не вижу веских причин не поддерживать эту систему.
* расширения в коробке по сути, ничем не отличаются от таких же разрабатываемых во вне, включая правила нумерации версий И если мы не используем для них субрепозитории, это не повод отменять правила.
* мы целенаправленно уходим от привязки версий расширения к релизам всей коробки (см. #1464), в том числе потому, что релизы системы у нас крайне не частые. А пользователь, который хочет плаигин без багов, не готов больше года сидеть в ожидании очередного релиза,  должен иметь возможность скачать и установить конкретный плагин.
* номер коммита может служить ориентиром только для разработчиков, но не пользователя — его не видно в админке, когда пользователь взял и накатил свежие файлы поверх текущей версии.
* система автоматизированного обновления, если таковая будет, может и должна ориентироваться только на версию расширения, но не коммиты, которые есть сущность только внутри VCS.

**Comment by Alex300** [comment]
Готово.
В мире есть огромное количество концепций, многие  из которых, мягко говоря, не являются разумными. Ну да ладно хочется играть в лидера - пожалуйста. У меня просто никак не хватает времени сделать форк. А пока я вынужден сидеть на Cotonti мне нужна от него в первую очередь стабильность. Не более.

Я коммитами затронул системные файлы. Версию движка стоит уже поднять до 0.9.20. Я исправлял не опечатку, внес серьезные изменения. Так что будьте последовательны до конца.

**Comment by macik** [comment]
Спасибо за исправления.

О последовательности — 
версия ядра (по историческим причинам) у нас не вписывается в полной мере в формат семантической нумерации:

> «Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.»
> — How should I deal with revisions in the 0.y.z initial development phase?
— The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

Все от того, что при очередном релизе мы увеличиваем на единицу патч номер, а не указатель минорной версии, **как следовало бы**. 
Поэтому приведенный тобой пример не корректен. В данном случае имело бы место 0.9.19-p*, вместо указанного тобой 0.9.20.

Надо отметить, что было предложение перейти к нормальной нумерации, и выпустить 0.10.0 вместо очередной 0.9.*. Но поддержки оно пока не нашло.
