### ISSUE TITLE
503 error when using function {PHP|cot_page_enum} in the file error.tpl

### ISSUE THREAD

**Issue by Roffun** [Cotonti/Cotonti#1511]
If you add the function {PHP | cot_page_enum}  to the file error.tpl, in the absence of the majority instead of 404 pages gives 503.

For example, on the website there is a category blog, a link to a non-existent address like //mysyte.this/blog/aa the transition issue as it should be 404.

But if there is a function {PHP | cot_page_enum} in the error.tpl file, when you open the specified address issues 503.

**Comment by Alex300** [comment]
fixed by https://github.com/Cotonti/Cotonti/commit/c8ca28bb07ff776a4038f8600d8077b0fa8da55a
Russian:
На страницах ошибок (404, 505)  и т.п. не стоит опцию $exclude_current устанавливать в true;
Добавлена проверка на этот момент.
