### ISSUE TITLE
cot_import_extrafields() title prefix 'page_' hardcoded

### ISSUE THREAD

**Issue by Alex300** [Cotonti/Cotonti#1517]
Russian:
system/extrafields.php стр. 153 функция cot_import_extrafields();
Префикс для вычисления имени поля 'page_' захардкожен. Модули должны сами указывать какой префикс использовать.

**Comment by Alex300** [comment]
Может что упустил, или в чем то ошибся - пишите - поправлю.

**Comment by macik** [comment]
Thanks, we will test it.
