### ISSUE TITLE
Users: Userlist filtering issues

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1532]
Reported here:
https://www.cotonti.com/forums?m=posts&q=8210&n=unread#unread

Think it may concern #1523 
@Dr2005alex , please look at it.

**Comment by Dr2005alex** [comment]
@macik  ok

**Comment by Dr2005alex** [comment]
@macik
I could not repeat this error
Глянь на своем сервере плиз.

**Comment by macik** [comment]
Checked on latest 0.9.19 and **can not been reproduced**.
Screenshots here: https://yadi.sk/d/T6cfWTOmuchNJ
(info posted in form thread).

So I'll waiting for a week and closing ticket if no addition details had been supplied.

**Comment by macik** [comment]
Closing now as no addition info had been provided,
