### ISSUE TITLE
Polls: «NAN» displayed in unvoted polls

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1533]
See screen:

![image](https://cloud.githubusercontent.com/assets/1009926/18114994/618f39ee-6f44-11e6-9cc5-cd29a8cc38b9.png)

**Comment by Roffun** [comment]
I tried to play at home, did not happen. I appear as expected.
![noerrors](https://cloud.githubusercontent.com/assets/12796217/18250627/48175800-738d-11e6-8574-9882bc06a94f.jpg)

**Comment by macik** [comment]
It's related to this line
https://github.com/Cotonti/Cotonti/blob/master/modules/polls/inc/polls.functions.php#L347

and spotted only in PHP v7.*:
https://3v4l.org/ShQVT
