### ISSUE TITLE
Mathcaptcha don't work with Yandex.metrika counter code

### ISSUE THREAD

**Issue by Wilder73** [Cotonti/Cotonti#1539]
При наличии кода Яндекс.Метрики, после отправки формы плагина Contact всегда выдается ошибка "Пример решен неверно", в результате чего данные не отправляются.

**Comment by Dr2005alex** [comment]
Отправка формы идет как гость или пользователем?

**Comment by Wilder73** [comment]
Гостем

**Comment by Wilder73** [comment]
Проверил все сборки до 0.9.15 - везде ошибка есть.

**Comment by Dr2005alex** [comment]
И ещё вопрос, в каком месте и каким образом стоит код яндекс метрики? по идее метрика на js а каптча нет....

**Comment by Wilder73** [comment]
В header.tpl, сразу после открывающего BODY. Пробовал ставить в footer.tpl, перед BODY - то же самое.

Сам сломал голову, потратил уже полдня. Тоже понимаю, что, по идее, проблемы не должно быть, но факт: убираю код Метрики - проблема исчезает, ставлю - появляется.

**Comment by Dr2005alex** [comment]
и еще в хроме нажимаем ctrl+shift+j и отправляем форму... смотрим какие ошибки в консоле вылезут... скрин сюда плиз

**Comment by Wilder73** [comment]
Пробовал на чистых сборках, конечно.

**Comment by Wilder73** [comment]
Ошибок нет, я бы увидел сразу.

**Comment by Dr2005alex** [comment]
Странно , а если убирать метрику работает?

**Comment by Wilder73** [comment]
Ну да :-) Кофе уже не помогает :-)

**Comment by Dr2005alex** [comment]
попробую повторить позже...  а это на чистом коте или на сборке фриланса к примеру?

**Comment by Wilder73** [comment]
На чистом, конечно. Я сейчас перебрал в обратном порядке все сборки от последней до 0.9.10, где капча "в коробке" появилась - одинаково.

**Comment by Wilder73** [comment]
Вот реальный пример (этот клиент мне и сообщил о проблеме): http://derevo-vologda.ru/contact
Сборка - 0.9.18.

**Comment by Wilder73** [comment]
Поставил сейчас совсем чистую сборку 0.9.19: http://test.edutver.ru/index.php?e=contact

**Comment by Wilder73** [comment]
Уточнение. Не работает не только Mathcaptcha. К примеру, плагин графической каптчи, выложенный на сайте Cotonti, выдает такую же ошибку. Видимо, дело не в плагине конкретной каптчи.

**Comment by seditio** [comment]
1. Можешь протестировать с кодом метрики внизу (footer.tpl)? У меня и Метрика и любые капчи вместе работают.
2. А в комментариях капча и Метрика тоже конфликтуют?

**Comment by Wilder73** [comment]
С кодом в футере тестировал сразу после обнаружения глюка - то же самое. В комментариях тоже проверил сразу.

**Comment by Wilder73** [comment]
> У меня и Метрика и любые капчи вместе работают.
Вот, чтобы не было сомнений, я и выложил на стандартный хостинг (Timeweb) чистую систему, даже вообще без каких-либо настроек.

**Comment by seditio** [comment]
А кроме как на этом Timeweb пробовал?

**Comment by macik** [comment]
Кстати, указанный выше тестовый сайт под FireFox у меня отрабатывает нормально. Под Chrome — да, дает ошибку. Интересно.

**Comment by macik** [comment]
Проверил на локальном хосте и на хостинге (том же таймвеб) 
http://stam.d3dev.ru/index.php?e=contact
— повторить не смог.

Сообщите набор установленных плагинов, и настройки метрики.

**Comment by Wilder73** [comment]
> Кстати, указанный выше тестовый сайт под FireFox у меня отрабатывает нормально. Под Chrome — да, дает ошибку. Интересно.
 
У меня ошибка возникает под любым браузером. 

> Сообщите набор установленных плагинов, и настройки метрики.

Сборка установлена стандартная - для чистоты эксперимента на шаге выбора расширений не устанавливал и не сбрасывал ни одной галочки. От настроек Метрики также не зависит - пробовал все комбинации функционала, с вебвизором, без него и т.д..

> А кроме как на этом Timeweb пробовал?

Пробовал на VDS и локально на OpenServer - результат одинаковый.

**Comment by macik** [comment]
> Пробовал на VDS и локально на OpenServer - результат одинаковый.

Тогда предложение такое — пакуй файлы и базу и присылай на  macik.spb@gmail.com  или выкладывай куда-нибудь.  Попробую на досуге потестить твой вариант.

**Comment by Wilder73** [comment]
Так это ведь будет то же самое, что скачать и установить стандартную сборку.

**Comment by macik** [comment]
Ну так стандартную я уже проверял и локально и на таймвебе — повторить глюк не могу. 
Какие будут предложения?

**Comment by Roffun** [comment]
> macik commented 7 days ago
Какие будут предложения?

Может избавиться от JS капчи в коробке вообще ?  C отключенным JS она все равно не защитит форму, submit сработает. Почему бы не заменить ее на php капчу, например на базе http://www.phpcaptcha.org  класса.  Готовый плагин есть у Alex300 : https://github.com/Alex300/SecurImageCaptcha-for-Cotonti

**Comment by seditio** [comment]
Контрпродуктивно

**Comment by macik** [comment]
@Wilder73 , для чистоты эксперимента проверь в браузерах без расширений —
для Chrome — запуск с ключом `--disable-extensions`
для FF — через меню "Справка" → "Перезапустить без дополнений"

**Comment by Dr2005alex** [comment]
Хоть убейте но не могу повторить у себя.... может какой пункт в яндекс-метрике особый ставить надо? есть мысли?

**Comment by Wilder73** [comment]
> Ну так стандартную я уже проверял и локально и на таймвебе — повторить глюк не могу.

Так ты же писал, что под хромом глюк получился.

> для чистоты эксперимента проверь в браузерах без расширений

Попробую - в понедельник-вторник доберусь до рабочего компьютера, проверю.

> Хоть убейте но не могу повторить у себя.... может какой пункт в яндекс-метрике особый ставить надо? есть мысли?

Грешил на включенный вебвизор, сразу же отключил - не помогло.

**Comment by macik** [comment]
> Так ты же писал, что под хромом глюк получился.
Это на твоем сайте. Но я не могу на нем дебаггер запустить.

**Comment by macik** [comment]
Closing now as can not reproduce.
