### ISSUE TITLE
SQL Errors with `only_full_group_by` SQL mode.

### ISSUE THREAD

**Issue by ghost** [Cotonti/Cotonti#1540]
Plugin Search result an error sql syntax when the search mode, the forum and the established forum.

> SQL error 42000: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'defa.p.fp_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by macik** [comment]
MySQL >=5.7.5  ?

**Comment by Roffun** [comment]
Tested on 5.6.21 hosting, and 5.7 local server

**Comment by macik** [comment]
Now there are several potential problem points for this SQL mode:

- [ ] modules\pfs\inc\pfs.admin.allpfs.php, line 34
- [ ] plugins\search\search.php, line 379
- [ ] plugins\tags\tags.tools.php, line 132

**Comment by macik** [comment]
[forums.install.sql](https://github.com/Cotonti/Cotonti/blob/master/modules/forums/setup/forums.install.sql) needs to be updated too.
