### ISSUE TITLE
Pagination does not appear through cot_page_enum

### ISSUE THREAD

**Issue by ghost** [Cotonti/Cotonti#1545]
pagination does not appear through cot_page_enum

**Comment by Alex300** [comment]
Oh, why are you done that. Why this terrible old-colonti style tags {PAGE_TOP_PAGEPREV}? What means 'TOP'. Why you removed most human friendly {PAGE_PAGEPREV}?

Russian.
Ого! И зачем Вы это сделали? Зачем сделали теги в старо-котовом стиле {PAGE_TOP_PAGEPREV}? И что в этом слове слове значит 'TOP'? Намек на то что их нужно ставить непременно вверху страницы? А если я захочу внизу?

Ладно еще Roffun - неопытный, но Macik. Ну хоть бы прочитал код прежде чем сливать. Пожалуйста не говори мне что это было осознано.

**Comment by Roffun** [comment]
> Ого! И зачем Вы это сделали? Зачем сделали теги в старо-котовом стиле {PAGE_TOP_PAGEPREV}? И что в этом слове слове значит 'TOP'? Намек на то что их нужно ставить непременно вверху страницы? А если я захочу внизу? Зачем удалили более человечный {PAGE_PAGEPREV}?

Ладно еще Roffun - неопытный, но Macik. Ну хоть бы прочитал код прежде чем сливать. Пожалуйста не говори мне что это было осознано.

**Для опытных, или по крайней мере тех кто себя таковыми считает**:
Я предложил сделать эту правку исходя из содержимого мастер ветки, если заглянуть в файл page.list.tpl и в page.functions.php, в функцию cot_page_enum, то в обоих случаях пагинация генерируется с помощью аналогичных тегов:

`'LIST_TOP_PAGINATION' => $pagenav['main']  и  	'PAGE_TOP_PAGINATION' => $pagenav['main']`
	
А в файле page.enum.tpl пагинация не работала, так как там были другие теги:
`	<p class="paging">{PAGE_PAGEPREV}{PAGE_PAGENAV}{PAGE_PAGENEXT}</p>`

Логично предположить (догадаться), что я предложил правку в TPL исходя из содержимого PHP. А если есть желание убрать приставку _TOP , то нужно было ее везде убирать, а не только в tpl файле, так как из-за этого у пользователей не работала пагинация, не все вникают в тонкости устройства расширений.

**Comment by Alex300** [comment]
Вы так и не ответили на вопрос, что там значит 'TOP'? Или осмысленность вторична?
В данном случае логичнее было поправить функцию **cot_page_enum**.

LIST_TOP_PAGINATION = тянется уже лет 10 еще со старого седитио или даже с LDU. В те времена списки страниц верстались (по крайней мере по убеждению Оливера.С) таблицами и пагинация действительно выводилась над списком. Отсюда и TOP в теге.

А дожил LIST_TOP_PAGINATION в таком виде до наших дней только благодаря кое какому консерватору которому непримелемо все новое и оптимальное.

То же самое касается тега PAGE_TITLE который и не title совсем а breadcrumbs.
Но эти 2-е сложились так исторически.
Но зачем то новое то городить?

**Comment by Roffun** [comment]
> Вы так и не ответили на вопрос, что там значит 'TOP'? Или осмысленность вторична?
> В данном случае логичнее было поправить функцию cot_page_enum.

Вы сами спросили и сами ответили тут же на свой вопрос:

> LIST_TOP_PAGINATION = тянется уже лет 10 еще со старого седитио или даже с LDU. В те времена списки страниц верстались (по крайней мере по убеждению Оливера.С) таблицами и пагинация действительно выводилась над списком. Отсюда и TOP в теге.

Я увидел что в новой функции не работает пагинация, заглянул в код и нашел причину, предложил поправить, основываясь на том коде который был по умолчанию, который по вашим же словам используется уже 10 лет. Я не ставил цель менять что-то в рабочем коде, я лишь нашел причину неработающей пагинации и предложил фикс.

Не пойму в чем проблема вообще, если хотите что-то улучшить, вносите правку. Лично мне абсолютно нет разницы, будет там LIST_TOP_PAGINATION или LIST_PAGINATION, главное чтобы работало.

**Comment by macik** [comment]
Давайте без лишних эмоций. 

0. На ГитХабе есть механизм комментариев, и механизм код-ревью. Им кроме меня может воспользоваться любой член команды разработчиков для комментирования поступающих запросов на правку (PR). Возможно стоит завести правило, какое минимальное время должен висеть пулл-реквест (с багофиксом) до вливания, чтобы все успели ознакомится...

1. Отвечая на вопрос зачем там `TOP` — в принципе незачем. Но @esclkm сделал эту функцию на основе ф-и `pagelist` из одноименного плагина (а он в свою очередь был по аналогии `LIST_*`). Полагаю делал он это не просто так, а для совместимости с указанным плагином и шаблонами сделанными под него.

2. Я слил эту правку вполне осознано. Так как есть баг, есть его вполне очевидное и быстрое решение. Зарываться сейчас в дебри как «должно быть правильно», с ломанием головы, а не пойдет ли что-то не так, сейчас (в условиях ограниченности своих ресурсов) я счел не целесообразным.

3. В целом я согласен, что здесь `{PAGE_*}`  или даже `{PAGELIST_*}` будут логичнее.

4. Что касается исправления детских болезней, типа `LIST_TOP_*` и `PAGE_TITLE` — есть конкретные предложения? Я вижу только вариант в ближайшем релизе поддерживать оба варианта (с последующим удалением старого формата через версию или две).

**Comment by Alex300** [comment]
Необходимо: 
- вернуть более человеко понятные теги вида "{PAGE_PAGEPREV}"
- поправить опечатку, вызванную копипастом, в функциии cot_page_enum, чтобы она могла работать с этими тегами.

**Comment by Kilandor** [comment]
So how about we look at it like this. cot_pagenav is used numerous times, with thin the virtually same calls to put the data into tags.
Why do we not just have a standardized function to build these tags similar to pages or users, simply supply the prefix for the area.
I realize pagenav would need to likely stay backwards compatible so either a new function or a new parameter could be added. It would save lots duplicate code and simply and standardize it.

**Comment by macik** [comment]
1. Sensible idea. It's better to make it as a separate function (e.g.) `cot_generate_pagenav`. And move there generation related code, like: [1](https://github.com/Cotonti/Cotonti/blob/0.9.19/modules/page/inc/page.functions.php#L822-L830) and [2](https://github.com/Cotonti/Cotonti/blob/0.9.19/modules/page/inc/page.functions.php#L911-L952)

2. Propose addition steps better customization and simplification —
Problems: 
 * In templates we use a hardcoded wrapper block (`p` in this case):
```php
<p class="paging">{PAGE_TOP_PAGEPREV}{PAGE_TOP_PAGENAV}{PAGE_TOP_PAGENEXT}</p>
```
 * We repeat these separate tags in templates over and over again...
 * We can not separate `prev` tag for real 'prev' and `first` «parts».

Suggestion:
 * Use Resource string for complete pagination block. Something like:
$R['pagenav_block'] = '&lt;p class="paging"&gt;{$first}{$prev}{$main}{$next}{$last}&lt;/p&gt;';

 * Add addition unified tag for whole pagination block {*_PAGENAV_BLOCK}
 * Unify returning array of `cot_pagenav()` to include: «first|prev|next|last».
 * Extend returning array of `cot_pagenav()` for whole generated pagenav block.

**Comment by Alex300** [comment]
It will be more correct to use "div" tag instead of the "p":

```
$R['pagination'] = '<div class="pagination">{$first}{$prev}{$main}{$next}{$last}</div>';
```

Or bootstrap like style:

```
$R['pagination'] = '<ul class="pagination">{$first}{$prev}{$main}{$next}{$last}</ul>';
```

All in all it is a good idea, but it must be moved to a separate issue.

**Comment by macik** [comment]
Enhancements discussion moved to #1551 .
