### ISSUE TITLE
`site_id` cookie check inconsistency

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1557]
Reported here:
https://www.cotonti.com/forums/42474?m=posts

got so much security logs like:
```
A variable type check failed, expecting COOKIE/ALP for 'ct66deea74dc5db9a1' :  TgxMDcxOmIzZGNmYjlkNGU2YzFkMjAzNzI3ZWIzMTM4YTRlMDBjYWY4MzBmYjM= - /
```
Think it caused as we try to check cookie value against ALP filter (regexp `'/[^a-zA-Z0-9\-_]/'`), but it consist a base64 coded string with `=` symbol at end, so import fails.

**Comment by Alex300** [comment]
Yes. Right. 'TXT' filter must be used here instead of 'ALP'
