### ISSUE TITLE
Плагин Hits. Глюк?

### ISSUE THREAD

**Issue by hammerteni** [Cotonti/Cotonti#1577]
На главной странице админки счетчик посещаемости далеко не за последние 7 дней. https://yadi.sk/i/kKQu1gr-3JWdb5

Целых 15 строк за период в три недели.

**Comment by seditio** [comment]
В первый раз такое вижу. На всех проектах с последними коммитами и без них все ок

**Comment by macik** [comment]
Тоже не сталкивался.
@hammerteni  Укажите версию сборки, и версию самого плагина.

**Comment by hammerteni** [comment]
Версия 
Cotonti 0.9.19
hits 1.1.2

**Comment by hammerteni** [comment]
Нашел причину. В файле hits.admin.home.php
https://yadi.sk/i/lVO-IDIe3JhpYK
В установочном файле то же что и на сайте. Поправил, все ок.

**Comment by macik** [comment]
Closed by 66d69f8c0d0da2014ffce7564c10d1b2dfa20f49
