### ISSUE TITLE
SQL errors in 0.9.20

### ISSUE THREAD

**Issue by afrostam** [Cotonti/Cotonti#1583]
I got this error when trying to edit a page. It doesn't happen all the time, but I'm getting database related errors like this every now and then, after upgrading to latest master version. Before that, I was at 0.9.14 and didn't encounter these at all.

SQL error 40001: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction [called at system/database.php line 676]

There are also 5 more "bullets" in the error report:
1) CotDB -> update(online) [called at whosonline.header.main.php line 47]
2) include (whosonline.header.main.php) [called at system/header.php line 87]
3) require_once (system/header.php) [called at page.edit.php line 136]
4) include (page.edit.php) [called at modules/page/page.php line 43]
5) require_once (page.php) [called at index.php line 176]

**Comment by macik** [comment]
What version of MySQL you are using?
Do you use some `InnoDB` tables?

**Comment by Alex300** [comment]
Closed as not confirmed
