### ISSUE TITLE
Official site down

### ISSUE THREAD

**Issue by PSalador** [Cotonti/Cotonti#1585]
http://www.cotonti.com/ is inaccessible.

**Comment by CrazyFreeMan** [comment]
game over

**Comment by Kilandor** [comment]
I have alerted Trustmaster to the issue, it should be resolved soon. The problem is it is not redirecting to https. For now you can just use https://www.cotonti.com

**Comment by seditio** [comment]
Problem is that I can only access cotonti.com via proxy from Russia (sometimes), US (sometimes), NL or France. Guess most of the Russian-speaking audience too.

**Comment by PSalador** [comment]
Yes, I access to site via Tor Browser.

**Comment by macik** [comment]
As for now investigation is in progress. Checking DNS as it experiencing some kind of DDoS.

**Comment by macik** [comment]
Please check site access once more.

**Comment by PSalador** [comment]
Yes, everything works.

**Comment by yusupovb** [comment]
Dnserror! Site available only with proxy.

**Comment by macik** [comment]
Yes. DNS has some problems.

As quick workaround (work me) — set Google DNS for my Network connection:
 for IPv4 service:
```
8.8.8.8
8.8.4.4
```
and for IPv6 access 
```
2001:4860:4860::8888
2001:4860:4860::8844
```

**Comment by Roffun** [comment]
This problem has something to do with the Cotonti branch ?

**Comment by Kilandor** [comment]
Just closing this is old. It doesn't need to be open.
