### ISSUE TITLE
The type attribute is unnecessary for JavaScript

### ISSUE THREAD

**Issue by Roffun** [Cotonti/Cotonti#1592]
The validator https://validator.w3.org/nu/ writes a warning:

> Warning: The type attribute is unnecessary for JavaScript resources.

**Comment by macik** [comment]
It may be actual only for HTML5. 

But as default we still use `XHTML 1.0 Transitional` in `Nemesis` theme. And as a result we required to specify `type` attribute.

For your theme, to be more correct you can add resource string altering in `themename.tpl`, as you suggest in pull request.

**Comment by Roffun** [comment]
I wanted that the assembly itself was relevant. Do not get attached to obsolete technologies. Use 1.0 is not recommended, at least 4.1, and in fact it is high time to go to httml 5.
And because of this obsolete code, all Cotonti users using modern capabilities (html5) will be forced to either make edits or watch in the validator "The type attribute is unnecessary for JavaScript resources".
**Information for consideration**:
https://html.spec.whatwg.org/multipage/
https://www.w3.org/TR/html5/
https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.cotonti.com%2F

**Comment by macik** [comment]
We can not drop some obsolete features at a time. We need to change it in complex for al case of usage within CMF. In case of your request it's at least some TPL files of default `Nemesis` theme.
