### ISSUE TITLE
Meta descriptions of pages restricted 255 characters

### ISSUE THREAD

**Issue by Roffun** [Cotonti/Cotonti#1597]
When adding / editing a meta description, pages are limited to <= 255 characters. Google has officially extended the search results snippets to a maximum character length of 320 characters.

https://www.seroundtable.com/google-extends-snippets-320-characters-24862.html
https://searchengineland.com/google-officially-increases-length-snippets-search-results-287596

**Comment by seditio** [comment]
Don't think it makes any sense

**Comment by Roffun** [comment]
Maybe, but nevertheless it is desirable to have the opportunity, and the Cotonti cuts 255 maximum.

**Comment by seditio** [comment]
Sizewise it makes more sense just to adjust fields in your own projests. 160 chars is enough.
