### ISSUE TITLE
Search plugin, php 7.2: warning when counting uncountable types

### ISSUE THREAD

**Issue by Roffun** [Cotonti/Cotonti#1602]
On version php 7.2, the search plugin issues: "Warning when counting uncountable types" if one word is entered in the search form. If this is a phrase, then there is no warning.

[Migrating to PHP 7.2.x](http://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types)

НА РУССКОМ:
**Плагин search, php 7.2: предупреждение при подсчёте неисчисляемых типов**
В версии php 7.2 плагин поиска выдает: «Предупреждение при подсчете неисчисляемых типов», если в форму поиска введено одно слово. Если это фраза, то предупреждения нет.

**Comment by eukraina** [comment]
+ спс!
