### ISSUE TITLE
Duplicate path links

### ISSUE THREAD

**Issue by seditio** [Cotonti/Cotonti#1611]
https://www.cotonti.com/extensions/pagelist
https://www.cotonti.com/extensions/extensions/navigation-structure/navigation-structure/pagelist
https://www.cotonti.com/extensions/extensions/extensions/navigation-structure/navigation-structure/navigation-structure/pagelist
etc
Canonical is good, still all the above links are valid, which is really no good.

**Comment by macik** [comment]
Issue already exists — #1441
