### ISSUE TITLE
The page_rating cell in the cot_pages table is not updated

### ISSUE THREAD

**Issue by ghost** [Cotonti/Cotonti#1617]
The ratings plugin makes updates to its table, but nothing changes in the page_rating cell, there is a constant value of 0.00.

На русском:
**Не обновляется ячейка page_rating в таблице cot_pages**.
Плагин ratings делает обновления в своей таблице, но ничего не изменяется в ячейке page_rating, там постоянное значение 0.00.

**Comment by macik** [comment]
На сколько помню, данное поле в модуле `page` может быть атавизмом, т.к. в свое время функционал рейтингов был вынесен из модуля в отдельный плагин. Таким образом в модуле это поле сохранилось лишь для обратной совместимости. Так что тут логичнее удалить это поле из модуля, чтобы оно не вводило в заблуждение.

**Comment by Dayver** [comment]
Может уже долой это поле page_rating ? Будут возражения?

**Comment by Alex300** [comment]
Надо посмотреть как работает плагин raitings. Используется ли оно им?
