### ISSUE TITLE
In login.php wiping settings after calling functions.php

### ISSUE THREAD

**Issue by almaz-free** [Cotonti/Cotonti#1620]
Two settings are set in the login.php file:
$env['location'] = 'users';
$env['ext'] = 'users';

and then the functions.php file is called by require_once, in which these settings are reset:
$env = array();

you need to move this two settings after calling require_once functions.php

**Comment by Alex300** [comment]
Fixed in a881f8971b2ef37dab3770f97d90ac6f60cac0be
