### ISSUE TITLE
Tag plugin: tag is not displayed during administration, if not attached to at least one element

### ISSUE THREAD

**Issue by Roffun** [Cotonti/Cotonti#1635]
If you delete or change the tag on the page, and it is the only one, then in the table cot_tags remains, but is not displayed anywhere.

Если вы удалите или измените тег на странице, и он единственный, то в таблице cot_tags останется, но нигде не отображается.

**Comment by Dr2005alex** [comment]
Самое интересное, что данная таблица где этот мусор собирается уже не используется в плагине. Это база данных для автозаполнения тегов. Вернее предложение тегов при вводе.  Есть код, но он включался в настройка плагина $cfg['plugin']['tags']['autocomplete'] и для него рекомендован плагин Recommends_plugins=autocomplete.

2 варианта, или допилить до нормального автозаполнения или почистить от ненужных функций и таблиц.

**Comment by Roffun** [comment]
В $db_tags хранится уникальное значение тега, а в $db_tag_references все случаи использования этого тега.
По сути дела $db_tags это словарь, не обязательно для авто - дополнения. 
Например кто-то захочет добавить предустановленный список тегов + сделает проверку на заполнение тегов только из словаря..

У меня уже есть новый плагин автодополнения, на чистом js, без необходимости jQuery ставить, работает как API, можно будет регистрировать функции для разных расширений через хук. Позже выложу.

Насчет словаря тегов - я переделал функционал tags под ингредиенты для модуля кулинарных рецептов, там словарь как раз нужен, и сделал администрирование неиспользуемых ингредиентов, плюс вырезал параметр tl, заменил на алиасы как для страниц. Тоже позже выложу.

Насчет тегов - делаю эксперимент, плагин utags, без поддержки tl (i-18) но с алиасами, и администрированием неиспользуемых тегов. Когда будет готов, тоже выложу, а принцип администрирования неиспользуемых тегов можно будет и в плагин tags добавить.

**Comment by Dr2005alex** [comment]
Данный фикс не полностью решает проблему. Необходимо на лету править данные. Неиспользуемые теги удалять сразу. плюс очистка неиспользуемых тегов при обновлении плагина один единственный раз. Т.е. делаем апдейт плагина с новой версией, при  обновлении удаляем мусор и в дальнейшем плагин не должен добавлять мусор. По моему так правильнее. 
Тоже сейчас занимаюсь этим вопросом. 
Дополнительно я сейчас проверяю все на новых версиях Mysql в строгом режиме + php 7 +

**Comment by Dr2005alex** [comment]
- [ ] {TAGS_RESULT_ROW_TAGS} should have its own resource #1527

- [ ] Page Taglist inconsistent when i18n used #1460

- [ ] Tags tools: Need to replace jQuery switch block with html #1643

В копилочку по плагину Tags
