### ISSUE TITLE
Make an existing repository a template

### ISSUE THREAD

**Issue by Roffun** [Cotonti/Cotonti#1638]
You need to make the Cotonti repository a template, to expand the development capabilities of assemblies. Since the fork imposes restrictions - 1 fork on 1 account, and at the same time, in order to offer editing, you must have a fork. It happens that it is easier to delete and fork again, but this imposes restrictions on the modification. Now there is a wonderful opportunity to make a copy in addition to the fork, for example for assembly. It is desirable to make it from the parent repository, which will definitely not be deleted, unlike the fork.

На русском:
Нужно сделать репозиторий Cotonti шаблоном, для расширения возможностей развития сборок. Так как форк накладывает ограничения - 1 форк на 1 аккаунт, и при этом чтобы предложить правку, нужно обязательно иметь форк. Бывает так, что проще удалить и форкнуть заново, но это накладывает ограничения на модификацию. Теперь появилась замечательная возможность помимо форка делать копию (template), например для сборки. Её желательно сделать из родительского репозитория, который точно не будет удаляться, в отличие от форка.

https://help.github.com/en/articles/creating-a-template-repository
https://help.github.com/en/articles/creating-a-repository-from-a-template

**Comment by Dr2005alex** [comment]
Хорошая возможность и идея.  Я так понял в новый форк  из шаблона будут автоматически идти правки из родителя (шаблона). Если это так, то очень удобно поддерживать свою разработку и не терять багфиксы из родителя (шаблона)

**Comment by macik** [comment]
Если что, доступ на изменение настроек репозитория у @trustmaster .

**Comment by Roffun** [comment]
Вот выдержка из описания (перевод):
> Создание репозитория по шаблону аналогично разветвлению репозитория, но есть и важные отличия:

Новая вилка включает в себя всю историю фиксации родительского репозитория, в то время как репозиторий, созданный из шаблона, начинается с одной фиксации.
Коммиты на вилку не отображаются в вашем графике вкладов, в то время как коммиты на репозиторий, созданный из шаблона, появляются в вашем графике вкладов.
Вилка может быть временным способом внесения кода в существующий проект, в то время как создание репозитория из шаблона быстро запускает новый проект.

> Если вы хотите создать новый репозиторий из содержимого существующего репозитория, но не хотите объединять свои изменения вверх по течению в будущем, вы можете скопировать репозиторий или, если репозиторий является шаблоном, использовать репозиторий в качестве шаблона.

Шаблон (template) отличается от форка, у них разные цели.

Форк может быть только 1 на аккаунт. Шаблонов может быть сколько угодно. И тот и другой помечаются ссылкой на родительский репозиторий, но шаблон не получает обновлений из родительского репозитория и не даёт возможности предлагать правки в него. Это новый проект, с указанием источника копирования, идеально подходит для новой сборки или различных экспериментов.

**Вывод**:
Для совместного развития движка обязательно нужен форк. Те кто участвуют в разработке, через него предлагают правки.
Для индивидуального проекта, в котором будут правки, не входящие в основной репозиторий (например свой загрузчик, расширения, библиотеки), идеально подходит клонированный шаблон.
Например **Cotonti Valensia** или сборка фриланс - это как раз тот случай, где вариант template подходит.

**Comment by Dr2005alex** [comment]
По сути шаблон это просто копия репозитория со ссылкой на него. Правки в шаблоне не видны этой копии на сколько я понял. Это совершенно новый проект. Тогда вопрос, а в чем прелесть шаблона? Просто взял скачал проект залил на github как свой и все тоже самое...
Может не все я понял?))

**Comment by Roffun** [comment]
> По сути проект из шаблона это просто копия репозитория со ссылкой на него. Правки в шаблоне не видны этой копии на сколько я понял. Это совершенно новый проект. Тогда вопрос, а в чем прелесть шаблона? Просто взял скачал проект залил на github как свой и все тоже самое...
> Может не все я понял?))

Если бы это было так, то вряд ли эту возможность создавали бы. А так появляется кнопка копирования, ссылка на родительскую сборку. Пишут что функционал будет расширяться.

**Comment by Dr2005alex** [comment]
Если будет фишка, такая как отслеживание изменений в родителе. Вот к примеру делаешь свою ветку, а багфиксы сливаешь из родителя в свою сборку. То это будет гуд. А так, на сегодняшний день пока эта фишка не более чем упрощение клонирования проекта в один клик ))
Подождемс...

**Comment by Roffun** [comment]
> Если будет фишка, такая как отслеживание изменений в родителе. Вот к примеру делаешь свою ветку, а багфиксы сливаешь из родителя в свою сборку.

Эти возможности есть у форка, в template они вряд ли появятся.
