### ISSUE TITLE
Tags tools: Need to replace jQuery switch block with html <details>

### ISSUE THREAD

**Issue by Roffun** [Cotonti/Cotonti#1643]
I suggest to replacie jQuery switch block with html <details>.

RU: Предлагаю заменить раскрывающийся блок jQuery на html <details>. 
[https://caniuse.com/#feat=details](https://caniuse.com/#feat=details)

**Comment by Dayver** [comment]
Это где такой блок у нас используется?

**Comment by Roffun** [comment]
tags.tools.tpl
