### ISSUE TITLE
Tags plugin does not work with i18n

### ISSUE THREAD

**Issue by Dr2005alex** [Cotonti/Cotonti#1644]
Коротко, плагин тегов не подхватывает локали. Теги для всех локалей одни и теже.
Например не прописывается выбранный язык по умолчанию. к примеру он текущий ru, далее создаем тег. Он прописывается в базу но без привязки к языку. Далее переключаемся на en и вводим теги для en языка. В итоге получаем для страницы на en тег прописанный в i18n для en, а при переходе на ru, высвечиваются все теги для данной страницы и ru и en

**Comment by Dayver** [comment]
Закрываю поскольку полностью дублирует #1460
