### ISSUE TITLE
Cotonti регистрация

### ISSUE THREAD

**Issue by Sigoy** [Cotonti/Cotonti#1657]
Привет.На оффсайте сламалась регистрация. Лечить кто будет или сайт умер окончатеьно? Зашла Cotonti в душу.. Сорян но писать больше некому.

**Comment by Alex300** [comment]
Привет!

У меня нет административных прав на Cotonti.com да и доступа к серверу тоже. Можешь вопросы задавать тут: [https://lily-software.com/forums](https://lily-software.com/forums)

**Comment by Alex300** [comment]
Fixed. Please feel free to register at https://www.cotonti.com/
