### ISSUE TITLE
Stored xss in forum messages

### ISSUE THREAD

**Issue by kukuxumushi** [Cotonti/Cotonti#1662]
Hi, we found a storage xss in forum message, which fires on theme page.

Version: master with this [commit](https://github.com/Cotonti/Cotonti/commit/41f751629f4a7bbc9b9bb27dcf5f682ba3a6ab84)

Steps to reproduse: 
1. Login as any user, that can write a messages to topics 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/32988979/188320895-5dd24e6c-65e8-4c70-bbe2-8ec893826b2d.png">

2. Create new theme with the following payload: `<noembed><img title="</noembed><img src onerror=alert(document.cookie)>"></noembed>`

<img width="851" alt="image" src="https://user-images.githubusercontent.com/32988979/188320597-dff364b9-263f-4353-abe9-2daee7752d29.png">
3. Go to forum page page
<img width="968" alt="Screenshot 2022-09-04 at 19 15 39" src="https://user-images.githubusercontent.com/32988979/188320781-230866de-a0ed-4fc2-aa01-2b68ebf7d1c4.png">

**Comment by Alex300** [comment]
Hi!

Thanks for issue report.

Is HTMLPurifier plugin is enabled on your site? This must be enabled if you are using an HTML (default) parser. I can't reprodice it.

**Comment by kukuxumushi** [comment]
So, i checked on this configuration, and its fires:
![51 250 80 34_admin php_m=config](https://user-images.githubusercontent.com/32988979/188397843-9390a6fa-b803-468c-b8b8-49173acdde76.png)
![51 250 80 34_admin php_m=config (1)](https://user-images.githubusercontent.com/32988979/188397852-cf281bf0-a6fe-4b07-b783-8e55171e659f.png)

Also, i tried to disable every HTML-pasrser, and its fires too.
<img width="995" alt="image" src="https://user-images.githubusercontent.com/32988979/188398730-6962174d-3c15-40ee-9237-74c0e1864283.png">
<img width="986" alt="image" src="https://user-images.githubusercontent.com/32988979/188398813-f5366f99-2cde-444f-8fbe-3e488e7c1894.png">
<img width="991" alt="image" src="https://user-images.githubusercontent.com/32988979/188398875-e0383552-da7d-4ef5-8cb4-a13c43d8adb8.png">

**Comment by Alex300** [comment]
hmm....

Please check if HTMLPurifier is running:
On extensions page:
![2022-09-05_11-35-39](https://user-images.githubusercontent.com/1021886/188407398-dd07818f-0573-49bf-afdb-7c55637ffce9.png)

I tried to reproduce it on that settings:

![2022-09-05_11-45-52](https://user-images.githubusercontent.com/1021886/188408350-abe80aa3-07a0-4b20-a165-55ac3f7debcd.png)

The only difference is Doctype. I'll try to test it with HTML5 doctype later.

You can turn of HTML supporting here: 
Admin panel -> Configuration -> Main Settings
![2022-09-05_11-39-38](https://user-images.githubusercontent.com/1021886/188408604-fb87ab0d-ea02-4195-a6d3-f64ea4ccb382.png)

**Comment by kukuxumushi** [comment]
Even with no HTML an XSS is working.
<img width="981" alt="image" src="https://user-images.githubusercontent.com/32988979/188409750-9afd3d09-6c98-48f3-80f5-a3374fab70e1.png">
<img width="819" alt="image" src="https://user-images.githubusercontent.com/32988979/188409879-576c7279-5c04-43c0-bc92-90264c396a91.png">

I can give you a credentials to our instance, if it will be helpful.

**Comment by Alex300** [comment]
Ok, thanks. Will test it

**Comment by kukuxumushi** [comment]
For members and administrators.

**Comment by Alex300** [comment]
I made several tests.
In every case
1) Set conig settings
2) Create new theme with the following payload: `<noembed><img title="</noembed><img src onerror=alert(document.cookie)>"></noembed>`


Cases:

1) Markup parser - HTML
   HTMLPurifier - enabled with Doctype html4/5
   CKeditor on/off
	result - negative

2) Markup parser - bbcode
   HTMLPurifier - disabled
     result - negative
	 
	But if you will change Markup parser to 'HTML' it will appear in topic that was created before chaging markup parser.
	
3) Markup parser - HTML
   HTMLPurifier - disabled.
     result - positive. But it is normal because there is no html filter.
	 
4) Markup parser - none	
   HTMLPurifier - enabled
     result - negative
	 output is filtered with htmlspesialchars()
	 output is: &lt;noembed&gt;&lt;img title=&quot;&lt;/noembed&gt;&lt;img src onerror=alert(document.cookie)&gt;&quot;&gt;&lt;/noembed&gt;
	 
	 
5) Markup parser - none	
   HTMLPurifier - disabled
      result - negative
	  output is filtered with htmlspesialchars()
	  But if you will change Markup parser to 'HTML' it will appear in topic that was created before chaging markup parser.

6) Direct call:
```
   $xss = '11111
        <noembed><img title="</noembed><img src onerror=alert(document.cookie)>"></noembed>
        <script>let a=123;</script>
        222222';
   echo htmlpurifier_filter($xss);
```
	
result - negative

    
Please keep in mind that with Markup parser 'HTML', HTMLPurifier is filtering values while them are importing form request e.g. before saving in DB. HTML field values loaded from the database are not filtered in any way before being displayed.

With Markup parser 'bbcode' or 'none' all output values are filtered with htmlspecialchars() function.

**Comment by kukuxumushi** [comment]
Hi, did you understand correctly, that you create a topic with payload, but the payload works not on the payload page, but on forum page, where you see the listing of topics?

<img width="842" alt="image" src="https://user-images.githubusercontent.com/32988979/188634545-04784abf-be14-4d78-bebb-8daa883125fd.png">

**Comment by Alex300** [comment]
Finally I reproduced it. On fresh install. No any parser, markup plugins installed. 

Fixed. Please test.

**Comment by kukuxumushi** [comment]
Its fixed now, thanks.
