### ISSUE TITLE
PFS - error messages if set "Thumbnails generation: - Disabled"

### ISSUE THREAD

**Issue by webitproff** [Cotonti/Cotonti#1677]
PFS module. If set "Thumbnails generation: - Disabled"  is set in the PFS config - we get the messages below.

Warning: Undefined variable $add_thumbnail in 
/modules/pfs/inc/pfs.main.php on line 509 
Warning: Undefined variable $add_image in 
/modules/pfs/inc/pfs.main.php on line 509

If set "Thumbnails generation: - GD1" OR "Thumbnails generation: - GD2", - vse zbs, no error messages!

if a file name contains special characters, we get the following message:

Warning: imagepng(): gd-png: fatal libpng error: bad parameters to zlib in 
/system/functions.php on line 2721 
Warning: imagepng(): gd-png error: setjmp returns error condition in 
/system/functions.php on line 2721

**Comment by Alex300** [comment]
> PFS module. If set "Thumbnails generation: - Disabled" is set in the PFS config - we get the messages below.
Fixed.

> if a file name contains special characters, we get the following message:
Can you provide an example please?

**Comment by webitproff** [comment]
> > PFS module. If set "Thumbnails generation: - Disabled" is set in the PFS config - we get the messages below.
> > Fixed.
> 
> > if a file name contains special characters, we get the following message:
> > Can you provide an example please?

https://forbiz.abuyfile.com/alex300/

1. логин и пароль:
Test_81

2. создать страницу
https://forbiz.abuyfile.com/alex300/page?m=add&c=usersposts

3. Жмем "Мои файлы" и заходим в папку "other", где уже есть картинка

или по ссылке
https://forbiz.abuyfile.com/alex300/pfs?f=4&c1=pageform&c2=rpagetext&parser=html

и сразу эта ошибка, еще даже ничего не загрузив, просто при просмотре папки, где уже есть один файл.

**Comment by webitproff** [comment]
uploaded updated files, updated. the error is gone.
vse zbs!
