### ISSUE TITLE
wrong way to translate forum structure names

### ISSUE THREAD

**Issue by webitproff** [Cotonti/Cotonti#1679]
I am in the admin.
Module "Forums", I click "Structure".
The "Internationalize Structure" button then asks you to select "locale".
I click on the link "English" and for some reason I get to the Internationalization of the structure of the "Page" module, this is in addition to the errors described earlier.

Нахожусь в админке.
Модуль "Форумы", нажимаю "Структура". 
Кнопка "Интернационализация структуры", затем просит выбрать "локаль".
Кликаю по ссылке "English" и я почему-то попадаю на Интернационализация структуры модуля "Page", это кроме ошибок, описанных ранее.

**Comment by Alex300** [comment]
The translation feature is implemented only for page categories. So "Internationalize Structure" button will be shown only for pages
