### ISSUE TITLE
We cannot open the corresponding forum structure category from the admin panel.

### ISSUE THREAD

**Issue by webitproff** [Cotonti/Cotonti#1680]
The test continues. Maybe the problem is not new, but it is worth paying attention, because its presence confuses, bewilders, and the feeling that the system is either buggy or not finalized.

1. Log in with administrator rights.
https://forbiz.abuyfile.com/alex300/
Login:
Admin
Pass:
AuI3lfyO

2. Open the structure of the "Forums" module. Each category of the structure of this module has an "open" button.
We press it in the hope that there will be magic and open the corresponding category, but only the main page of the "forums" module opens.
This problem is observed when "URL Editor" is enabled and when it is disabled. It doesn't matter if we are trying to open a parent category or a child category from a structure.
When we try to open a specific category from the "Forums" module structure from the control panel, we observe that the links (aliases) in the address bar change depending on the category, but the result is inexorably the same - only the main page of the forums. But that's not all.
3. It becomes more interesting when on the main page of the "Forums" module, nevertheless, by clicking on the category name, for example "Off-topic", we successfully enter this category.
From the backend, the transition to the category does not work, but from the frontend, it works ...
4. Now for the links themselves, which are formed on the category:
4.1 Here is a link to the "Off-topic" category from the site control panel, looking through the structure of the "Forums" module -
https://forbiz.abuyfile.com/alex300/index.php?e=forums&c=offtopic
4.2 And here is a link to the "Off-topic" category of the main forums module on the frontend, -
https://forbiz.abuyfile.com/alex300/index.php?e=forums&m=topics&s=offtopic

This really causes bewilderment and the feeling that the content management system is not well developed or is some kind of bug.

**RU**

Тест продолжается. Может проблема не новая, но стоит обратить внимание, потому что её наличие вгоняет в ступор, в недоумение, и ощущение того, что система или баговая или не доработанная.

1. Заходим как администратор.
2. Открываем структуру модуля "Форумы". У каждой категории структуры этого модуля есть кнопка "открыть".
Нажимаем её в надежде, что будет магия и откроем соответствующую категорию, но открывается только главная страница модуля "форумы".
Эта проблема наблюдается при включенном "URL Editor" и когда он отключен. Не важно, пытаемся открыть  родительскую категорию или дочернюю.
Когда из панели управления пытаемся открыть конкретную категорию из структуры модуля "Форумы", то наблюдаем, что ссылки (алиасы) в адресной строке меняются в зависимости от категории, но результат неумолимо один - только главная страница форумов.
Но это не всё.
3. Интереснее становится после того, как на главной странице модуля "Форумы", все же кликая по названию категории, например "Off-topic", - мы успешно заходим в эту категорию.
Из бэкэнда переход в категорию не работает, а из фронтэнда, - работает...

4. Теперь по самим ссылкам, которые формируются на категорию:

4.1 Вот такую ссылку на категорию "Off-topic" из панели управления сайтом, просматривая структуру модуля "Форумы", - 
https://forbiz.abuyfile.com/alex300/index.php?e=forums&c=offtopic
4.2 И вот такая ссылка на категорию "Off-topic" главной модуля форумов на фронтэнде, - 
https://forbiz.abuyfile.com/alex300/index.php?e=forums&m=topics&s=offtopic

Это правда вызывает недоумение и ощущение того, что система управления сайтом не доработана или это какой-то баг.

**Comment by Dayver** [comment]
Так было и ранее. Потому что раздел Структура конкретно для модуля Форум изначально не был предназначен, вернее даже не так - когда то Структура это были листинги для Страниц, а у Форума был свой функционал задания структуры. Тоесть не было единого функционала управления структурами модулей и каждый имел свой инструмент задания структуры модуля, и она лежала в отдельной таблице, и код управления ею был у каждого свой (но во многом дублировался).

Поскольку во много эти инструменты были похожи то в ходе улучшения движка листинги страниц превратили в Структуру которую универсализировали таким образом что бы сделать что с помощью одного инструмента можно задавать структуру разным модулям в том числе и в самописных модулях и не нужно было пилить с нуля свою структуру в модуле или копировать код из базовых модулей потому теперь это можно делать на базе готовых универсальных функций. 

Потому исходя из предыстории нужно понимать что функционал кнопки Открыть в структуре достаточно простой - открывать страницу модуля с адресом &с=код_категори .... для модуля Страниц этого достаточно, а вот для форумов нет потому что у форумов есть отличия в адресе страницы в зависимости от уровня вложенности. Тоесть категория форума нулевого уровня - Секция форума и формат адреса страницы один, а вот категория форума вложенных уровней это уже Раздел форума и формат урла другой. Этих особенностей функционал структуры не знает поскольку он как бы универсальный, от того и получаются не функциональными кнопки Открыть в разделе Структура для модуля Форум.

Во времена тех глобальных трансформаций которые пережил движок такая мелочь казалось ерундой на фоне того огромного скачка улучшения кода который превратился в функционал Структур модулей. Сейчас, конечно, когда мало кто помнит как это работало раньше то такое поведение конечно кажется багом.

Доработать этот момент конечно стоит. Но хотелось бы что бы не забывали что сейчас движок уже не просто CMS но уже и CMF, что подразумевает, что тонкую настройку кое-где все таки нужно делать самостоятельно, а значит при разработке модулей с использованием Структуры могут быть вот такие нюансы, а значит в базовом модуле Форум нужно решить эту проблему так что бы для самописных модулей это могло бы настраиваться так же.

**Comment by webitproff** [comment]
> Так было и ранее. .... нужно решить эту проблему так что бы для самописных модулей это могло бы настраиваться так же.

Спасибо за пояснение!

**Comment by Alex300** [comment]
Please test it and close if it is ok

**Comment by webitproff** [comment]
> Please test it and close if it is ok

К сожалению ничего не поменялось. Проблема остается.

Unfortunately, nothing has changed. The problem remains.

**Comment by webitproff** [comment]
but after these edits, the categories of the structure of the Page module stopped opening from the admin panel.

но после этих правок, перестали открываться из админки категории структуры модуля Page.

**Comment by webitproff** [comment]
I propose to return the ability to the Page module to open categories from the admin panel, and in the forums module, since this does not work as it should, that is, it does not have a logical conclusion, the "open" button in the "Forums" structure should be completely hidden or removed. and close this issue for good.

RU
Предлагаю вернуть возможность модулю Page открывать категории из админки, а в модуле форумов, раз это не работает как нужно, то есть не имеет логического завершения, - кнопки "открыть" в структуре "Форумы" вовсе скрыть или убрать. и закрыть этот вопрос навсегда.

**Comment by Alex300** [comment]
Oops, sorry. Due to inattention, I forgot to add a check if the category belongs to the forum. "Hooked" everything. It should work now. Fixed.

RU
По невнимательности забыл добавить проверку на то что категория принадлежит форуму. "Зацепил" все. Сейчас должно работать

**Comment by webitproff** [comment]
closed
