### ISSUE TITLE
Hooks. File is not exists. Solution.

### ISSUE THREAD

**Issue by Alex300** [Cotonti/Cotonti#1688]
Now we are including hooks this way:
```php
/* === Hook === */
foreach (cot_getextplugins('pm.tags') as $pl) {
    include $pl;
}
/* ===== */
```
But there may not be the including file if the extension was removed from the disk, but not in the admin panel, or a new version of the extension was uploaded and it is not contain this file, and you have not yet clicked "Update".

As a result, we get a Warning that we are including a non-existent file. And then the system can't send headers, if necessary, because the output to the browser has already been. And if it's Ajax returning Json, then the output generally breaks.

Solution:

The cot_getextplugins() function should check for the file existence. If it doesn't exist then don't include it in the result array and add a warning and log it:
```php
if (!file_exists($pl)) {
	if(!empty(cot::$usr['isadmin'])) {
		cot_message(cot::$L['fileNotExists'] . ': ' . $pl, 'warning');
	}
	cot_log(cot::$L['fileNotExists'] . ': ' . $pl, 'ext');
}
```

The result is improved reliability. And only administrators will see the messages about missing files.

It is needed to check all uses of this function. Perhaps checking should be optional.

### UPD
Hooks API enhancement moved to separate issue: https://github.com/Cotonti/Cotonti/issues/1714

---
[RU]
### 1) Проверка существования подключаемого файла
Сейчас у нас хуки подключаются так:
```php
/* === Hook === */
foreach (cot_getextplugins('pm.tags') as $pl) {
   include $pl;
}
/* ===== */
```
Но файла хука может не быть, если расширение было удалено с диска, а в админке нет, или была загружена новая версия расширения в которой нет этого файла, и еще не нажали "Обновить".

В результате получаем Warning о том что подключаем несуществующий файл. И тут уже система не может отправить заголовки, если нужно, т.к. вывод в браузер уже был. А если это Ajax возвращающий Json, то вывод вообще ломается.

Решение:

Функция `cot_getextplugins()` должна проверять существование файла, если его нет, то не ключать его в массив, который она возвращает, добавлять предупреждение и логировать это. Как то так:
```php
if (!file_exists($pl)) {
	if (!empty(cot::$usr['isadmin'])) {
		cot_message(cot::$L['fileNotExists'] . ': ' . $pl, 'warning');
	}
	cot_log(cot::$L['fileNotExists'] . ': ' . $pl, 'ext');
}
```
В итоге повышается надежность. А сообщения о том что не хватает каких то файлов увидит только администратор.

Нужно проверить все использования этой функции. Возможно проверка должна быть опциональной.

### UPD
Улучшение API хуков вынесено в отдельную задачу: https://github.com/Cotonti/Cotonti/issues/1714

**Comment by Dayver** [comment]
Я считаю эта проверка(она достаточно разумна и полезна) должна быть исключительно опциона, пусть включена по умолчанию из коробки(в этом есть смысл) но возможность её отключить должна быть.

**Comment by Dayver** [comment]
Решение хорошее но есть "но"

- Оооочень опасное решение выбрать в качестве имени переменной просто **$event** , а не хотя бы с префиксом _cot__ или что то вроде **$hook_event** , идеал конечно это **$cot_hook_event** (хотя вероятно соглашусь оно избыточно)  ... такое имя $event - достаточно обширное и может применятся много где (только в самой коробке это имя встречается как минимум в классе кеша, функции пагинации и под эту функцию в [строковых ресурсах](https://github.com/Cotonti/Cotonti/blob/master/system/resources.rc.php#L46) для этой функции ... что уже говорить о сторонних расширениях), а потому есть достаточно обоснованный риск конфликтов. И если в коробке такие пересечения можно проконтролировать то старые сторонние расширения просто перестанут работать или начнут глючить, а новые получат, неявные для разработчика, ограничения на именование своих переменных.

- в [строке](https://github.com/Cotonti/Cotonti/blob/master/system/functions.php#L1220) файла functions.php определение пути действительно необходимо или это остатки старого кода? понимаю что непосредственно даного коммита это не касается но всё же.

**Comment by Alex300** [comment]
1) Да, согласен. Переделаю на **$cot_event**.

2) В [строке](https://github.com/Cotonti/Cotonti/blob/master/system/functions.php#L1220) файла functions.php определение пути - это остаток старого кода. Тоже думал над ним. Вроде если его убрать, ничего поломаться не должно. Но потестировать не получилось. Не смог вот так сразу запустить функцию `cot_outputfilters()` в реальных условиях. Пока оставил как есть.

**Comment by Alex300** [comment]
- [ ] Заменить `$event` на `$cot_event`
- [ ] Обновить инструкцию https://www.cotonti.com/docs/ext/extensions/ext_hooks сделав ту же замену

**Comment by Dayver** [comment]
А почему не пойти другим путём .. [здесь](https://github.com/Cotonti/Cotonti/blob/master/system/functions.php#L253) возвращать что то типа
```
....
$extPlugins[$hook . '.' . инкрементная_переменная] = $fileName;
....
```
Тогда вызовы в системе и расширениях сделать типа:
```
foreach (cot_getextplugins('footer.first') as $hook => $pl) {
    include $pl;
}
```
тогда не нужно будет городить истории с переменными которые всего то лишь хранят имя вызываемого хука и передавать его имя через ключ возвращаемого массива (а что бы ключи не схлопывались то добавлять инкремент). Это не решает проблему "вложености" но значительно упрощает систематику выполнения вызовов хуков

А еще я бы вопреки стилю сократил все вызовы _крючков_ в однострочный вариант
и вместо 
```
    /* === Hook === */
    foreach (cot_getextplugins('import.date') as $pl) {
        include $pl;
    }
    /* ===== */
```
было бы лаконичное
```
    ...
    foreach (cot_getextplugins('import.date') as $hook => $pl) include $pl; /* === Hook === */
    ...
```
ну по крайне мере там где в подавляющем большинстве где внутри цикла происходит единственная операция инклуда. Тогда код будет напоминать тот лаконичный и чистый минималистичный стиль который любят многие и в целом является характеристикой кота в целом.

**Comment by Alex300** [comment]
Это тоже не решит проблему вложенности. Вот такая схема получается:

```php
foreach (cot_getextplugins('footer.first') as $hook => $pl) {
    // обработчик с вложенным хуком
    // ... 
    foreach (cot_getextplugins('footer.some.ext') as $hook => $pl) {
        // Вызов вложенного хука. Перезаписал переменную $hook
	// ... 
    }
    // ...
    // тут $hook будет уже перезаписана
}
```
Как вариант можно хуки вызывать так:

```php
$cot_someExtUpperHook = isset($hook) ? $hook : null;
foreach (cot_getextplugins('footer.first') as $hook => $pl) {
    include $pl;
}
$hook = $cot_someExtUpperHook;
```

Также это применимо и к переменной из первого (откаченного) варианта:
```php
$cot_someExtUpperHook = isset($cot_event) ? $cot_event : null;
$cot_event = 'footer.first';
foreach (cot_getextplugins($cot_event) as $pl) {
    include $pl;
}
$cot_event = $cot_someExtUpperHook;
```
Тогда схема выполнения будет примерно такой:
```php
foreach (cot_getextplugins('footer.first') as $hook => $pl) {
	// обработчик с вложенным хуком
	// ...
	$cot_someExtUpperHook = $hook;
	foreach (cot_getextplugins('footer.some.ext') as $hook => $pl) {
		// Вызов вложенного хука. Перезаписал переменную $hook
		// ... 
	}
	$hook = $cot_someExtUpperHook;

	// ...
	// тут $hook содержит правильное значеник
}
```

Вот тут вопрос. Стоит ли так усложнять код ради того чтобы иметь возможность в обработчике получить код хука.

**Comment by Dayver** [comment]
А если через переменную переменных (правда нужно от точки избавится заменой) _концептуально_ вот так:
    ...
    $hook = 'import.date';
    foreach (cot_getextplugins($hook) as $$hook => $pl) {
        include $pl;
        ....
        $hook = 'import.date.done';
        foreach (cot_getextplugins($hook) as $$hook => $pl) {
            include $pl;
            ....
        }
        ....
    }
    ...
Всего одна строчка ... замену точки только вкорячить

**Comment by Dayver** [comment]
Так уже наклёвывается АПИ хуков) Ну и логично раньше просто функционал крючков был а сейчас уже и отслеживание вызываемого хука с нормальной работой вложенности и логирование сбоев .... еще много плюшек опциональных можно добавить)

**Comment by Alex300** [comment]
Ага )))

Вот еще идея. Сделать класс Hook.
```php
foreach (Hook::fireEvent('footer.first') as $pl) {
   include $pl;
}
Hook::end();
```

Или короткий вариант записи:
```php
foreach (Hook::fireEvent('footer.first') as $pl) { include $pl; } Hook::end();
```

`Hook::fireEvent($hook, $cacheHandlers = false)` возвращает массив с файлами обработчиками и запоминает файл, откуда был вызван хук и код хука. При этом он может опционально сохранить во внутренней переменной список обработчиков, чтобы его можно было использовать при вызове хука в цикле.

`Hook::currentEvent()` вернет код текущего хука и файл, в котором он был вызван

`Hook::end()` удалит из стека текущую пару файл/код хука.

Этот класс сам будет вести статистику того какие хуки вызывались во время работы скрипта, логировать ошибки и т.п.

функции `cot_getextplugins()` и `cot_get_caller()` оставляем для обратной совместимости. Объявляем как **deprecated** и они будут запрашивать данные у класса `Hook`.

**Comment by Dayver** [comment]
Ну статистика по хукам была бы весьма полезной для процесса оптимизации - посмотрел логи и статистику, и видишь вот в этом месте хуки отрабатывают долго\много и это место можно было бы пересмотреть и упростить ... потому что серверные способы отслеживания не дают такой точной информации по локализации проблемных мест ... естественно така статистика должна быть выключена по умолчанию и включатся как и дебаг только на время и только осознанно. Потому если бы у хуков было АПИ то и реализовать статистику уже было бы реально и на стороне если её нет из коробки

**Comment by Dayver** [comment]
Тут только вопрос насколько этот весь массив изменений и плюшек добавит накладных расходов ... непонятно на чем можно было бы протестировать различие а делать искуственные тесты порой нет смысла

**Comment by Alex300** [comment]
Единственный момент, возможно это однострочный вызов хука в цикле:

Сейчас:
```php
$extp = cot_getextplugins('page.list.tags');
foreach ($pages as $row) {
    ...
    foreach ($extp as $pl) {
        include $pl;
    }
    ...
}
```

Будет:

```php
foreach ($pages as $row) {
    ...
    /* === Hook === */
    foreach (Hook::fireEvent('page.list.tags', true) as $pl) { include $pl; } Hook::end();
   /* ========== */
    ...
}
```
И я не уверен, что увеличение нагрузки (если оно вообще будет) будет сильно заметно даже при большой нагрузке.

**Comment by Dayver** [comment]
Однострочность даже в варианте вызова внутри цыкла это несомненно еще один плюс, а не только красота кода. Читаемость и "понятность" того как это выглядит сейчас (в модуле Страниц это заметно) хромает особенно для новичков. С внецыкловыми хуками проблемы нет чётко и понятно а вот цыклы это прям совсем не ахти.

И если накладные расходы не вырастают то остаётся резюмировать - обговоренный вариант позволит:
- основная цель - проверка и логирование сбоев когда нет файла по которому зарегистрирован хук
- дополнительная цель - внутри хука появляется возможность легко опредить по какому хуку произошёл вызов
- такое определение будет корректно работать во вложенных многоуровневых случаях
- сопуствующая плюшка - до этого и так красывый и лаконичный вызов хука превращается в еще более красивый однострочный вариант с ооогромным бонусом для некрасивых цыкличных вызовов теперь это такой же однострочный вариант (разработчики плагинов которые хуками пользуются не тольк с целью внедрятся по хукам но и раставлять в свох расширениях свои хуки это точно оценят)
- еще бонус в том плане что функционал выделяется и централизируется в отдельное АПИ (пусть даже пока и небольшое)
- в ближайшей перспективе это АПИ можно дополнить ведением статистики и отладки ... для разработчиков которые сопровождают свои проекты(а не просто сделал сайт и свалил) долгое время, это облегчит оптимизацию и развитие проектов ... а при должной документации так же поможет тем кто получил готовый проект в наследство и должен разобратся как его отладить

**Comment by Alex300** [comment]
API хуков вынесено в отдельную задачу: https://github.com/Cotonti/Cotonti/issues/1714
