### ISSUE TITLE
The search plugin has found topics in closed forum sections

### ISSUE THREAD

**Issue by Kabak** [Cotonti/Cotonti#1691]
The search plugin has found topics in closed forum sections and creates links to these sections. The content of these links is available for reading by anyone, even an unregistered visitor. 

Pages don't have this problem.

**Comment by Kabak** [comment]
Seems,  Search plugin found but visitors could not read.   ( cash issue )

**Comment by Alex300** [comment]
[RU]
Надо проверить 2 кейса:

1) Тема находится в категории на чтение которой у пользователя нет прав. Т.e. у этой категории  https://www.site.ru/admin/rights?g=1 (g=1 - гости - для примера) в Module Forums структура сняты все галки.

    Выдает ли результаты поиска из этой категории?
    Дает ли посмотреть если зайти в темы по прямым ссылкам?

2) Тема находится в категории на чтение которой у пользователя есть права, но сама тема приватная (доступна только создателю и модераторам/админам)

Теже вопросы.

Это бы очень помогло.

**Comment by Kabak** [comment]
1)  Выдаёт  на форуме.  На страницах  не выдаёт 

2) Как только я включил права ТОЛЬКО НА ЧТЕНИЕ но всем включая неавторизованным, то поиск перестал выдавать ссылки неавторизованным пользователям. 
Создаёт ссылки и показывает текст из этих топиков, но по ссылкам не пускает с ошибкой доступа

**Comment by Alex300** [comment]
Пока не тестировал. Позже проверю. Если все ок, то можно закрывать issue

**Comment by Kabak** [comment]
Вроде работает.  Если что-нибудь найду, то напишу.

**Comment by Alex300** [comment]
Please test it. If there are some errors, reopen this issue
