### ISSUE TITLE
When posting new message on forum got SQL error HY093: Invalid parameter number: number of bound variables does not match number of tokens

### ISSUE THREAD

**Issue by Kabak** [Cotonti/Cotonti#1692]
( message posted but with error message )

Fatal error
2023-03-31 12:35

SQL error HY093: Invalid parameter number: number of bound variables does not match number of tokens

#0 /var/www/dacha/system/database.php(368): cot_diefatal('...')
#1 /var/www/dacha/modules/forums/inc/forums.functions.php(211): CotDB->query('...', Array)
#2 /var/www/dacha/modules/forums/inc/forums.posts.php(149): cot_forums_resyncTopic(3, false)
#3 /var/www/dacha/modules/forums/forums.php(35): include('...')
#4 /var/www/dacha/index.php(180): require_once('...')

**Comment by Kabak** [comment]
Appeared when creating new post on forum.  Does not appear if editing posts

**Comment by Alex300** [comment]
I apologize. Typo in the code
