### ISSUE TITLE
plugin recentitems has bug

### ISSUE THREAD

**Issue by Kabak** [Cotonti/Cotonti#1697]
Plugin recentitems does not show any new items for today added on pages.

**Comment by Kabak** [comment]
may be its normal ...    the list disappears at the next minute

**Comment by Kabak** [comment]
not disappearing at forums

**Comment by Kabak** [comment]
{PAGE_ROW_COUNT}  is not updating correctly   ( in dbase correct value )

**Comment by Alex300** [comment]
Please test it. If there are some errors, reopen this issue
