### ISSUE TITLE
Plugin Search giving multiple warrning messages

### ISSUE THREAD

**Issue by Kabak** [Cotonti/Cotonti#1702]
Deprecated: Implicit conversion from float 12353.5 to int loses precision in /var/www/apcfix/plugins/search/inc/search.functions.php on line 55 , 64 , 79 

presents of warning depends from searching string !

**Comment by Alex300** [comment]
Please provide a search string example to reprodice it

**Comment by Kabak** [comment]
время автоном

**Comment by Dayver** [comment]
Судя по всему это уже исправлено в 86a1d2e5794c72e55401bf8311e3657062892b74 перекачайте файл [plugins/search/inc/search.functions.php](https://github.com/Cotonti/Cotonti/blob/master/plugins/search/inc/search.functions.php) будет ли появляться снова эта ошибка?

**Comment by Kabak** [comment]
Yes, seems problem disappeared
Thank you.
