### ISSUE TITLE
Cotonti 0.9.23 image icons issue

### ISSUE THREAD

**Issue by prbt2016** [Cotonti/Cotonti#1722]
Hello,

I was in the process of manual installation of Cotonti 0.9.23 on Centos 7 with PHP 5.6, MYSQL 5.7, Apache 2.2.
However after successful installation on logging in . I see that the image icons for Configuration, Structure, Extensions , Others are not shown, only text is shown, whereas they are shown for Home and users. 

Following is the screenshot of the same, also there is 404 on following image url's as shown in the image below : 

![test_cotonti](https://github.com/Cotonti/Cotonti/assets/17871448/d5e11b77-2c8b-4bb2-b7c0-512adcc6a646)

Could you please replicate this at your end and resolve the same ?.

**Comment by Alex300** [comment]
I can't reproduce it.   
Is the server response really 404? 
Maybe the antivirus is blocking them?  
Are these images really on the server?

**Comment by Dayver** [comment]
> I can't reproduce it. Is the server response really 404? Maybe the antivirus is blocking them? Are these images really on the server?

Тоже ловил эту проблему но разобраться времени не было.  И 404 и точно антивирус не причём.

**Comment by seditio** [comment]
Может это быть связано с некорректным автоопределением https на версиях, где еще не было опции forcehttps? У меня был единственный баг в админке из-за этого и очень похож по симптомам.

**Comment by Dayver** [comment]
> Может это быть связано с некорректным автоопределением https на версиях, где еще не было опции forcehttps? 

Кстати очень вероятно - когда ловил этот баг то припоминаю могло быть связано с https
