### ISSUE TITLE
Remove or turn off cot_log_import()

### ISSUE THREAD

**Issue by Alex300** [Cotonti/Cotonti#1724]
[RU]
Функция `cot_log_import()` логирует события, когда при импорте данных из запроса, реальный тип принимаемого параметра не совпадает с ожидаемым.

Например:
```php
$someVar = cot_import('someVar', 'G', 'INT');
```
Ожидает что `$_GET['someVar']` содержит целое число и отфильтрует принимаемые данные соответственно. Но если вместо числовых данных (или приводимых к таковым), будет строка, то это будет залогировано в БД. 

При большой посещаемости сайта, а тем более если какой-нибудь робот шлет кучу запросов на сайт, или DDos это может вызывать серьезную нагрузку на БД.

Нужно или 
1) Совсем убрать логирование несоответствия типов импортируемых данных. Кто ими пользуется? Кому то интересно, с какого IP передается куча неправильных данных?
или  
2) Cделать опциональным и отключенным по-умолчанию.

**Comment by Kabak** [comment]
Сделать опциональным и отключённым по умолчанию.  Зачем урезать потенциальный и готовый функционал ? ( риторический )

Вдруг, ком-нибудь понадобится для анализа

**Comment by Dayver** [comment]
Согласен, в одном проекте используется для составления бан листов поскольку на основе таких логов детектируются сканирующие уязвимости боты

**Comment by Dayver** [comment]
Но и обратную сторону медали тоже подтверждаю - когда не надо создаёт лишнюю нагрузку на БД ... так что отключатору быть

**Comment by Alex300** [comment]
Плюс тут еще возможна трудноуловимая ошибка.

Например программист в своем расширении написал
```php
cot_import('somevar', 'G', 'ALP')
```
а надо было
```php
cot_import('somevar', 'G', 'TXT')
```
и приходит там значение не просто с буквенное, но с другими символами. И срабатывает эта проверка при каждом запросе. Оно и будет логировать каждый раз... сильно увеличивая размер таблицы
