### ISSUE TITLE
Unify CAPTCHA tags

### ISSUE THREAD

**Issue by seditio** [Cotonti/Cotonti#1732]
Right now we have {USERS_REGISTER_VERIFYIMG}, {COMMENTS_FORM_VERIFY_IMG}, {CONTACT_FORM_VERIFY_IMG}, maybe more
Suggestion is to unify the postfix as XXX_VERIFY_IMG so as to avoid confusion and misspelling

**Comment by Alex300** [comment]
The following replacements have been made:   

**modules\users\tpl\users.register.tpl**   
`{USERS_REGISTER_VERIFYIMG}` -> `{USERS_REGISTER_VERIFY_IMG}`   
`{USERS_REGISTER_VERIFYINPUT}` -> `{USERS_REGISTER_VERIFY_INPUT}`   
						
**plugins\comments\tpl\comments.tpl**   
`{COMMENTS_FORM_VERIFYIMG}` -> `{COMMENTS_FORM_VERIFY_IMG}`   
`{COMMENTS_FORM_VERIFY}` -> `{COMMENTS_FORM_VERIFY_INPUT}`   

**plugins\contact\contact.php**   
`{CONTACT_FORM_VERIFY}` -> `{CONTACT_FORM_VERIFY_INPUT}`
