### ISSUE TITLE
Plugin Recent Items improvements

### ISSUE THREAD

**Issue by Kabak** [Cotonti/Cotonti#1735]
1) Please add to Recent Items plugin the creation of tags for the last person who wrote on the FORUM_ROW_LASTPOSTER forum. I'm interested in an **avatar**, or better  complete information about FORUM_ROW_LASTPOSTER.

Thank you

2) Add to recent pages config ability to set sorting by filed: page_created or page updated 
3) Ограничить вывод последних публикаций/постов периодом. Например выводить материалы не старше недели/(1,3,6,9)месяцев/(1,2,3)года

**Comment by Kabak** [comment]
Create all available tags about last poster and topicstarter.  requred on the main site page for me

Thank you

**Comment by Kabak** [comment]
Also will be great to add into Recent Items plugin ability to stick some news at the top of news line permanently 

Thank you

**Comment by Alex300** [comment]
Use `FORUM_ROW_FIRST_POSTER_XXX` tags for first poster, `FORUM_ROW_LAST_POSTER_XXX` for last poster.  

>  ability to stick some pages at the top of news line permanently
Not sure if stick pages feture is related to Recent Items. You can use `cot_page_enum()`  or **Page List** plugin for it.
