### ISSUE TITLE
Functions in admin.cache.disk.php

### ISSUE THREAD

**Issue by seditio** [Cotonti/Cotonti#1741]
Functions in admin.cache.disk.php shall be moved to an external functions-file that you can include via
`cot_incfile('core', 'smth');`

**Comment by Alex300** [comment]
[RU]
Посмотри реализацию \Cache::clear() - system/cache.php:L1504
Можно сбрасывать как отдельные виды кеша, так и весь.

В простейшем случае
```php
if (Cot::$cache) {
    Cot::$cache->clear();
}
```
Полностью зачистить дисковый кеш, как в админке:
```php
Cot::$cache->disk->clear(null, null);
```

**Comment by seditio** [comment]
Все ок
