### ISSUE TITLE
Users filters and sorting

### ISSUE THREAD

**Issue by Alex300** [Cotonti/Cotonti#1757]
All filters must work via a GET request. The filters must correctly form the Canonical URL and meta title

[RU]
Все фильтры должны работать через GET запрос. Фильтры должны правильно формировать Canonical URL и meta title.   Фильтр по группам не должен работать для скрытых групп, если у пользователя нет соответствующих прав.  
Если группы или страны не существует - отдавать 404

**Comment by seditio** [comment]
404 или системное сообщение (не существует / нет доступа)?

**Comment by Kabak** [comment]
в версии на 25-е декабря пропали иконки для сортировки  списка пользователей ASC / DESC
