### ISSUE TITLE
When creating or editing page '<' replaced with &lt in page description and displayed incorrectly

### ISSUE THREAD

**Issue by Kabak** [Cotonti/Cotonti#1765]
{PAGE_DESC}  teg problem

page.functions.php

strings 298 - 304

```
                htmlspecialchars($page_data['user_name']) : '',
            'DESC' => (isset($page_data['page_desc']) && $page_data['page_desc'] != '') ?
                htmlspecialchars($page_data['page_desc']) : '',
            'DESC_OR_TEXT' => (isset($page_data['page_desc']) && $page_data['page_desc'] != '') ?
                htmlspecialchars($page_data['page_desc']) : $text,
            'DESC_OR_TEXT_CUT' => (isset($page_data['page_desc']) && $page_data['page_desc'] != '') ?
                htmlspecialchars($page_data['page_desc']) : $text_cut,
```

seems  should be 

```
            'DESC' => (isset($page_data['page_desc']) && $page_data['page_desc'] != '') ?
                $page_data['page_desc'] : '',
            'DESC_OR_TEXT' => (isset($page_data['page_desc']) && $page_data['page_desc'] != '') ?
                $page_data['page_desc'] : $text,
            'DESC_OR_TEXT_CUT' => (isset($page_data['page_desc']) && $page_data['page_desc'] != '') ?
                $page_data['page_desc'] : $text_cut,
```

**Comment by Alex300** [comment]
see https://github.com/Cotonti/Cotonti/issues/1763

This is not a bug. Page description is plain text field and it should be processed by `htmlspecialchars()` before output

**Comment by Alex300** [comment]
There are page screenshots.
see one more time: https://github.com/Cotonti/Cotonti/issues/1763 )))

**Comment by Kabak** [comment]
I have read that.   And '<' storing in DBASE as &lt not '<'
[https://i.gyazo.com/5570efbf38be2c76a1b209351afb6599.png](url)

**Comment by Alex300** [comment]
Try to edit page or create a new one after code update. It shoult work. I cant reproduce this issue.

**Comment by Kabak** [comment]
forums.sections.php &  forums.topics.php  still have a problem

https://i.gyazo.com/5d1c5c459c2d38f561cf3679811469f1.png
https://i.gyazo.com/14fdf6c50e562f4eb3d8c074160f4d33.png

**Comment by Alex300** [comment]
Please try now

**Comment by Kabak** [comment]
Doesn't changed

**Comment by Alex300** [comment]
If it is nof fixed with last commit (https://github.com/Cotonti/Cotonti/commit/c4a231613588f2b4fea430cb008848a716510119). Can you please provide more info. Template and tag names.
I can't reproduce it.

![Снимок экрана 2024-01-24 204000](https://github.com/Cotonti/Cotonti/assets/1021886/a291dee1-a311-461c-9027-ef3f92033ebd)

![Снимок экрана 2024-01-24 195739](https://github.com/Cotonti/Cotonti/assets/1021886/b4e62178-82fe-4934-af91-c13e58533bbd)

![Снимок экрана 2024-01-24 195759](https://github.com/Cotonti/Cotonti/assets/1021886/5bb1f459-730d-4a28-b485-8aac5ace06c3)

**Comment by Kabak** [comment]
forums.sections.tpl  {FORUMS_SECTIONS_ROW_LASTPOST} 

forums.topics.tpl  {FORUMS_TOPICS_ROW_TITLE} , {FORUMS_TOPICS_ROW_DESC}
