### ISSUE TITLE
Function  cot_string_truncate() warning 

### ISSUE THREAD

**Issue by Kabak** [Cotonti/Cotonti#1770]
Warning: Array to string conversion in /var/www/blog/system/cotemplate.php on line 1873

usage : {PAGE_ROW_TEXT|cot_string_truncate($this,150,true,false,'...')}

Not always , but if truncating text contains some sequence.  For example  blocks of code , but not every block containing code trigger that warning.

**Comment by Alex300** [comment]
Can you please provide a text example which triggers this error?

**Comment by Kabak** [comment]
<h4>Как проверить наличие модуля&nbsp;<strong>PM</strong>&nbsp;в системе ?</h4>

<p><small>( Аналогично по имени проверяется наличие и активность любого модуля. )</small></p>

<pre class="brush:xml;">
&lt;!-- IF {PHP.cot_modules.pm} --&gt;
    &lt;!-- IF {PHP.usr.messages} --&gt;
        &lt;li&gt;&lt;a class=&quot;glowing&quot; href=&quot;{PHP|cot_url(&#39;pm&#39;)}&quot; title=&quot; 
                 {PHP.L.Private_messages}&quot;&gt;{PHP.L.Private_Messages}&lt;/a&gt;&lt;/li&gt;
    &lt;!-- ELSE --&gt;
    &lt;li&gt;&lt;a class=&quot;&quot; href=&quot;{PHP|cot_url(&#39;pm&#39;)}&quot; title=&quot;{PHP.L.Private_messages}&quot;&gt; 
                  {PHP.L.Private_Messages}&lt;/a&gt;&lt;/li&gt;
    &lt;!-- ENDIF --&gt;
&lt;!-- ENDIF --&gt;</pre>

**Comment by Kabak** [comment]
seems that triggering [https://i.gyazo.com/a69c0a2ab84bfaeffc3b4e39aaa38f0c.png](url)

**Comment by Alex300** [comment]
Хм. Похоже оно пытается переданный текст распарсить и выполнить.

Как быстрый фикс, могу предложить условие:
```
if (is_string($argument) && mb_strpos($argument, '{') !== false) {
```
заменить на 
```
if (is_string($argument) && mb_strpos($argument, '{') === 0) {
```
Позже продебажу и сделаю постоянный фикс.

**Comment by Alex300** [comment]
I fixed CoTemplate. Please test it. If it is ok, will make hot fix release.

**Comment by Alex300** [comment]
Thanks for bug report.
I fixed template. Please test it. If it is ok, I'll make fixed release next week.

**Comment by Kabak** [comment]
Seems it's working now

Thank you.
