### ISSUE TITLE
CKEditor need to update.

### ISSUE THREAD

**Issue by webitproff** [Cotonti/Cotonti#1771]
CKEditor send alarm: `This CKEditor 4.22.1 version is not secure. Consider [upgrading to the latest one](https://ckeditor.com/ckeditor-4-support/), 4.24.0-lts.`

**Comment by Alex300** [comment]
In master branch this message is [tunred off](https://github.com/Cotonti/Cotonti/blob/master/plugins/ckeditor/lib/config.js). 

In Siena 0.9.25, we will try [to upgrade to version 5](https://github.com/Cotonti/Cotonti/issues/1655). I would have done it earlier, but the differences are too significant.

4.24.0-lts is not free version and can not be included to the Cotonti "box"

**Comment by Alex300** [comment]
Related to #1655
