### ISSUE TITLE
FILE expression works incorrect with var in it & XTPL cache enabled

### ISSUE THREAD

**Issue by seditio** [Cotonti/Cotonti#1791]
When used in a TPL-file with 
`$cfg['xtpl_cache'] = true;`
expression
`{FILE "themes/{PHP.theme}/inc/{PHP.al}.commonname.tpl"}`
gives same output for all pages. Works properly only when XTPL cache is disabled.

**Comment by Alex300** [comment]
[RU]

Шаблонизатор устроен так:

`\XTemplate::restart()` выполняет метод `\XTemplate::compile()` в котором сначала инклудит файлы, заменяя конструкции вида `{FILE "..."}` содержимым этих файлов, тем самым получая полный шаблон. Потом разбирает его на блоки, индексы и теги.
Полученные данные кеширует.

Если данные в кеше есть, то `\XTemplate::compile()` не выполняется и используются данные из кеша.

Вариант решения:   
Вынести обработку тегов `{FILE "..."}` из  `\XTemplate::compile()` и собирать шаблон в `\XTemplate::restart()`. По готовому коду вычислять хеш и использовать его как ключ в именах файлов.

Минусы:  
- Поскольку замена производится регулярным выражением, получим небольшое снижение производительности (возможно и не принципиальное) т.к. будет выполняться одно регулярное выражение для каждого шаблона.

Плюсы:  
- Больше гибкости

Ну и для каждого значения `{PHP.someVar}` в конструкции `{FILE "themes/{PHP.theme}/inc/{PHP.someVar}.commonname.tpl"}` получим по 3 файла в кеше. Нельзя злоупотреблять, иначе кеш будет сильно разрастаться. Если есть шанс что таких вариантов будет много, лучше использовать функцию-виджет в шаблоне: `{PHP|commonname({PHP.someVar})}`
