### ISSUE TITLE
Split base.js code into separate files.

### ISSUE THREAD

**Issue by Alex300** [Cotonti/Cotonti#1794]
[RU]

Очень неудобно вести разработку, когда все компоненты собраны в одном файле.
Можно разделить файл [js/base.js](https://github.com/Cotonti/Cotonti/blob/master/js/base.js) на отдельные компоненты и потом собирать при помощи [Gulp](https://gulpjs.com/) в один файл. Тем более, что количество компонентов будет расти.

Структура может выглядеть так:

```
js
  sourse
    src
      Cot.js           - класс фасад на JS
      Pagination.js    - какой то новый компонент
      PopupMessage.js  - какой то новый компонент
      base.js          - наш нынешний base.js

    gulpfile.js
    package.json
    package-lock.json

  base.js           - результирующий JS файл
  base.min.js       - Gulp позволяет и минифицировать файл
``` 

Но при таком подходе файл **js/base.js** править будет уже нельзя т.к. он будет перезаписываться при сборке. Правки можно вносить в файлы в папке **js/source/src**. Но это касается только **Cotonti Team**.

Для вебмастеров, использующих Cotonti, ничего не изменится. **js/base.js** и весь его функционал будет доступен как и прежде.

**Comment by Dayver** [comment]
> Но при таком подходе файл **js/base.js** править будет уже нельзя т.к. он будет перезаписываться при сборке. Правки можно вносить в файлы в папке **js/source/src**. Но это касается только **Cotonti Team**.

А разве это проблема?
